import * as THREE from 'three';
import {surface} from './terrain-surfaces.mjs';

const S=1/50,stone=new THREE.MeshStandardMaterial({map:surface('rock'),color:0x9badb4,roughness:.92}),trim=new THREE.MeshStandardMaterial({color:0xbda271,metalness:.55,roughness:.42}),dark=new THREE.MeshStandardMaterial({color:0x37433f,roughness:.92});
const at=(x,y,h=0)=>new THREE.Vector3(x*S,h,y*S);
function add(parent,g,m,x=0,y=0,z=0){const n=new THREE.Mesh(g,m);n.position.set(x,y,z);n.castShadow=true;n.receiveShadow=true;parent.add(n);return n;}
function column(parent,r,h,m,y=0){return add(parent,new THREE.CylinderGeometry(r,r*1.05,h,12),m,0,y,0);}
export function citadel(type,team){const group=new THREE.Group(),base=type==='base',tint=team===0?0x68bdea:0xeb6e58,light=new THREE.MeshStandardMaterial({color:tint,emissive:tint,emissiveIntensity:1.25,roughness:.24,metalness:.25});
  column(group,base?1.08:.54,.15,dark,.075);column(group,base?.97:.48,.12,trim,.19);column(group,base?.85:.44,.24,stone,.37);
  const sides=base?6:4;for(let i=0;i<sides;i++){const a=i*Math.PI*2/sides,r=base?.78:.34;const buttress=new THREE.Group();buttress.position.set(Math.cos(a)*r,.52,Math.sin(a)*r);buttress.rotation.y=-a;group.add(buttress);const shaft=add(buttress,new THREE.BoxGeometry(base?.16:.17,base?.54:1.02,.25),stone,0,base?.05:.28,0);shaft.rotation.z=base?-.3:-.12;add(buttress,new THREE.BoxGeometry(.19,.07,.3),trim,0,base?.34:.8,0);add(buttress,new THREE.OctahedronGeometry(.095),light,0,base?.45:.92,.025);}
  if(!base){column(group,.24,.81,stone,.92);column(group,.3,.12,trim,1.42);column(group,.26,.16,dark,1.56);}
  if(base){const petal=new THREE.Shape();petal.moveTo(-.13,0);petal.bezierCurveTo(-.5,.28,-.42,.96,-.14,1.2);petal.bezierCurveTo(.08,.64,.15,.3,.13,0);petal.closePath();const shape=new THREE.ExtrudeGeometry(petal,{depth:.1,bevelEnabled:true,bevelSize:.035,bevelThickness:.02,bevelSegments:2,steps:1});for(let i=0;i<6;i++){const fin=new THREE.Group();fin.rotation.y=i*Math.PI/3;group.add(fin);add(fin,shape,stone,0,.2,.68);add(fin,new THREE.OctahedronGeometry(.055),light,0,1.2,.78);}}
  const crystal=add(group,new THREE.OctahedronGeometry(base?.43:.23,0),light,0,base?1.13:1.85,0);crystal.scale.set(.85,base?1.35:1.6,.85);group.userData.crystal=crystal;
  const ring=add(group,new THREE.TorusGeometry(base?.48:.31,.018,6,32),trim,0,base?1.1:1.86,0);ring.rotation.x=Math.PI/2;ring.rotation.y=.35;
  const groundRing=add(group,new THREE.RingGeometry(base?1.25:.56,base?1.28:.58,64),new THREE.MeshBasicMaterial({color:tint,transparent:true,opacity:.2,side:THREE.DoubleSide,depthWrite:false}),0,.026,0);groundRing.rotation.x=-Math.PI/2;groundRing.castShadow=false;group.traverse(n=>{if(n.isMesh&&![stone,trim,dark].includes(n.material))n.material.userData.owned=true;});return group;
}
export function footSoldier(team){const group=new THREE.Group(),cloth=new THREE.MeshStandardMaterial({color:team===0?0x386475:0x824d3f,roughness:.7}),metal=new THREE.MeshStandardMaterial({color:0x9ba4a0,metalness:.55,roughness:.4});
  const body=add(group,new THREE.CapsuleGeometry(.11,.23,3,8),cloth,0,.38,0);body.scale.z=.75;
  for(const s of [-1,1]){add(group,new THREE.CylinderGeometry(.045,.055,.23,8),dark,s*.063,.135,0);const arm=add(group,new THREE.CapsuleGeometry(.047,.17,2,8),metal,s*.16,.39,0);arm.rotation.z=s*.17;}
  const helm=add(group,new THREE.SphereGeometry(.107,12,8),metal,0,.63,0);helm.scale.y=1.1;add(group,new THREE.BoxGeometry(.135,.025,.04),dark,0,.65,.09);
  add(group,new THREE.BoxGeometry(.024,.34,.055),metal,.2,.32,0);add(group,new THREE.BoxGeometry(.13,.025,.04),trim,.2,.22,0);add(group,new THREE.BoxGeometry(.14,.24,.035),cloth,-.19,.33,.06);group.traverse(n=>{if(n.isMesh&&![stone,trim,dark].includes(n.material))n.material.userData.owned=true;});return group;
}
export function guardian(camp){const group=new THREE.Group(),boss=camp==='boss',size=boss?1.8:1,color=camp==='power'?0x526a80:camp==='renewal'?0x628470:0x666471,rock=new THREE.MeshStandardMaterial({map:surface('rock'),color,roughness:.88}),glow=new THREE.MeshStandardMaterial({color:boss?0xe8ac70:0x86cfff,emissive:boss?0xd97831:0x338dcc,emissiveIntensity:1.2});
  const mass=add(group,new THREE.DodecahedronGeometry(.34,1),rock,0,.7,0);mass.scale.set(1.35,1.25,.9);for(const s of [-1,1]){add(group,new THREE.DodecahedronGeometry(.19,0),rock,s*.18,.2,0);const arm=add(group,new THREE.DodecahedronGeometry(.25,1),rock,s*.48,.6,0);arm.scale.y=1.5;const horn=add(group,new THREE.ConeGeometry(.085,.31,8),trim,s*.15,1.18,0);horn.rotation.z=-s*.4;}
  const head=add(group,new THREE.DodecahedronGeometry(.18,1),rock,0,1.04,.09);for(const s of [-1,1])add(group,new THREE.SphereGeometry(.025,8,6),glow,s*.055,1.06,.247);const core=add(group,new THREE.OctahedronGeometry(.12),glow,0,.76,.28);group.userData.crystal=core;group.scale.setScalar(size);group.traverse(n=>{if(n.isMesh&&![stone,trim,dark].includes(n.material))n.material.userData.owned=true;});return group;
}
function routeDistance(x,y,routes){let best=Infinity;for(const r of routes)for(let i=1;i<r.length;i++){const a=r[i-1],b=r[i],dx=b[0]-a[0],dy=b[1]-a[1],t=THREE.MathUtils.clamp(((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy),0,1);best=Math.min(best,Math.hypot(x-a[0]-dx*t,y-a[1]-dy*t));}return best;}
function ribbon(scene,points,width,material,height=.02){const curve=new THREE.CatmullRomCurve3(points.map(p=>at(p[0],p[1],height)),false,'catmullrom',.02),samples=150,vertices=[],uv=[],indices=[];let length=0,previous=null;for(let i=0;i<=samples;i++){const t=i/samples,p=curve.getPoint(t),tangent=curve.getTangent(t),normal=new THREE.Vector3(tangent.z,0,-tangent.x).normalize();if(previous)length+=p.distanceTo(previous);previous=p;for(const side of [-1,1]){vertices.push(p.x+normal.x*width*side,p.y,p.z+normal.z*width*side);uv.push(side===-1?0:1,length/2.5);}if(i<samples){const a=i*2;indices.push(a,a+1,a+2,a+1,a+3,a+2);}}
  const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();const road=add(scene,g,material);road.castShadow=false;return road;
}
export function buildBattlefield(scene,routes,obstacles,bushes){
  let seed=7249;const rand=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646;};
  const grassMap=surface('grass'),groundMat=new THREE.MeshStandardMaterial({map:grassMap,color:0x83b3a8,roughness:1});
  groundMat.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\ndiffuseColor.rgb = mix(vec3(0.035,0.085,0.07),diffuseColor.rgb,0.72);');};
  const ground=add(scene,new THREE.PlaneGeometry(90,70),groundMat,15,-.03,10);ground.rotation.x=-Math.PI/2;ground.castShadow=false;
  const meadow=new THREE.InstancedMesh(new THREE.CircleGeometry(1,10),new THREE.MeshBasicMaterial({color:0x285e50,transparent:true,opacity:.22,depthWrite:false}),90),patch=new THREE.Object3D();for(let i=0;i<90;i++){patch.position.set(rand()*30,.001,rand()*20);patch.rotation.x=-Math.PI/2;patch.scale.set(.6+rand()*1.2,.4+rand()*.9,1);patch.updateMatrix();meadow.setMatrixAt(i,patch.matrix);meadow.setColorAt(i,new THREE.Color().setHSL(.38+rand()*.10,.35,.19+rand()*.13));}meadow.castShadow=false;scene.add(meadow);
  const dirtMat=new THREE.MeshStandardMaterial({map:surface('dirt'),color:0x7b9c98,roughness:1});
  const roadMat=new THREE.MeshStandardMaterial({map:surface('stone'),color:0x9babb6,roughness:.95,side:THREE.DoubleSide});
  for(const route of routes){ribbon(scene,route,.99,dirtMat,.01);ribbon(scene,route,.84,dark,.024);ribbon(scene,route,.77,roadMat,.032);}
  const riverPoints=[[620,-200],[740,240],[730,520],[870,760],[950,1200]];
  ribbon(scene,riverPoints,1.40,dirtMat,.017);
  ribbon(scene,riverPoints,1.18,new THREE.MeshBasicMaterial({color:0x45a4a7,transparent:true,opacity:.24,side:THREE.DoubleSide,depthWrite:false}),.020);
  const water=new THREE.MeshStandardMaterial({color:0x17495a,roughness:.25,metalness:.30,transparent:true,opacity:.92,side:THREE.DoubleSide});
  const waterTime={value:0};water.onBeforeCompile=shader=>{shader.uniforms.riftTime=waterTime;shader.vertexShader='uniform float riftTime;\n'+shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.y += sin(position.x * 5.0 + riftTime * 1.2) * 0.007 + cos(position.z * 4.0 - riftTime) * 0.008;');};
  ribbon(scene,riverPoints,1.05,water,.022);
  const flowers=new THREE.InstancedMesh(new THREE.ConeGeometry(.11,.43,5),new THREE.MeshStandardMaterial({color:0x7956a3,roughness:.72}),100),flower=new THREE.Object3D();for(let i=0;i<100;i++){const y=rand()*950+25,x=680+y*.16+(i%2?1:-1)*(70+rand()*12);flower.position.copy(at(x,y,.16));flower.rotation.set((rand()-.5)*.5,rand()*6,(rand()-.5)*.5);flower.scale.setScalar(.55+rand()*.7);flower.updateMatrix();flowers.setMatrixAt(i,flower.matrix);}scene.add(flowers);
  // Camps are separate dirt clearings, with enough room to fight around the guardian.
  for(const [x,y,r]of [[640,330,1.1],[860,670,1.1],[750,500,1.35]]){const camp=add(scene,new THREE.CircleGeometry(r,48),dirtMat,x*S,.025,y*S);camp.rotation.x=-Math.PI/2;camp.castShadow=false;for(let i=0;i<8;i++){const a=i/8*Math.PI*2,rock=add(scene,new THREE.DodecahedronGeometry(.1+rand()*.08,0),stone,x*S+Math.cos(a)*r,.11,y*S+Math.sin(a)*r);rock.scale.y=.6;}}
  for(const o of obstacles){const r=o.radius*S;for(let i=0;i<5;i++){const a=i/5*Math.PI*2,rock=add(scene,new THREE.DodecahedronGeometry(r*.52,1),stone,o.x*S+Math.cos(a)*r*.35,.25+rand()*.08,o.y*S+Math.sin(a)*r*.35);rock.scale.set(1,.65+rand()*.3,.75);rock.rotation.set(rand()*.4,rand()*6,rand()*.2);}const top=add(scene,new THREE.DodecahedronGeometry(r*.54,0),stone,o.x*S,.55,o.y*S);top.scale.set(1,.5,.8);}
  for(let k=0;k<obstacles.length;k++){const o=obstacles[k],r=o.radius*S;for(let i=0;i<7;i++){const a=(o.x<750?Math.PI:0)+i*.31,b=a+.29,shape=new THREE.Shape();shape.absarc(0,0,r*.88,a,b,false);shape.absarc(0,0,r*.66,b,a,true);shape.closePath();const geometry=new THREE.ExtrudeGeometry(shape,{depth:.47,bevelEnabled:true,bevelSize:.028,bevelThickness:.028,bevelSegments:1,curveSegments:4,steps:1});geometry.rotateX(-Math.PI/2);add(scene,geometry,stone,o.x*S,.025,o.y*S);const cap=geometry.clone();cap.scale(1.05,.12,1.05);add(scene,cap,dark,o.x*S,.49,o.y*S);}}
  // Blade clusters mark the exact hiding areas; decorative foliage stays outside lanes.
  const bladeGeometry=new THREE.BufferGeometry();bladeGeometry.setAttribute('position',new THREE.Float32BufferAttribute([-.04,0,0,.04,0,0,.022,.30,.035,0,.48,.065],3));bladeGeometry.setIndex([0,1,2,0,2,3]);bladeGeometry.computeVertexNormals();const leafMat=new THREE.MeshStandardMaterial({color:0x578a69,roughness:.9,side:THREE.DoubleSide});
  const blades=new THREE.InstancedMesh(bladeGeometry,leafMat,bushes.length*110),dummy=new THREE.Object3D();let count=0;for(const b of bushes)for(let i=0;i<110;i++){dummy.position.copy(at(b.x+(rand()-.5)*b.w,b.y+(rand()-.5)*b.h,.03));dummy.rotation.set(0,rand()*Math.PI*2,0);dummy.scale.setScalar(.8+rand()*.55);dummy.updateMatrix();blades.setMatrixAt(count,dummy.matrix);blades.setColorAt(count++,new THREE.Color().setHSL(.32+rand()*.04,.3,.26+rand()*.14));}blades.castShadow=true;scene.add(blades);
  const treePoints=[];for(let i=0;i<320;i++){const x=rand()*2100-300,y=rand()*1500-250;if(routeDistance(x,y,routes)<110||Math.hypot(x-120,y-840)<200||Math.hypot(x-1380,y-160)<200||Math.abs(x-(680+y*.16))<95||[[640,330],[860,670],[750,500]].some(p=>Math.hypot(x-p[0],y-p[1])<125)||obstacles.some(o=>Math.hypot(x-o.x,y-o.y)<o.radius+30)||bushes.some(b=>Math.abs(x-b.x)<b.w&&Math.abs(y-b.y)<b.h))continue;treePoints.push({x,y,s:.6+rand()*.45});}
  const trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.055,.13,1.45,7),new THREE.MeshStandardMaterial({color:0x544836,roughness:1}),treePoints.length),crowns=new THREE.InstancedMesh(new THREE.PlaneGeometry(1.4,1.1),new THREE.MeshStandardMaterial({map:surface('foliage'),color:0xa8c8b4,alphaTest:.42,roughness:1,side:THREE.DoubleSide}),treePoints.length*4);
  for(let i=0;i<treePoints.length;i++){const p=treePoints[i];dummy.position.copy(at(p.x,p.y,.73*p.s));dummy.rotation.set(0,p.x,0);dummy.scale.setScalar(p.s);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);for(let n=0;n<4;n++){const a=n/3*Math.PI*2;dummy.position.copy(at(p.x,p.y,(1.36+n*.1)*p.s));dummy.position.x+=Math.cos(a)*.27*p.s;dummy.position.z+=Math.sin(a)*.27*p.s;dummy.rotation.set(-Math.PI/2+n*.25,a+p.x,rand()*.2);dummy.scale.set(p.s*1.3,p.s*.95,p.s*1.1);dummy.updateMatrix();crowns.setMatrixAt(i*4+n,dummy.matrix);crowns.setColorAt(i*4+n,new THREE.Color().setHSL(i%7===0?.70:.37+rand()*.04,i%7===0?.36:.24,.58+rand()*.16));}}
  trunks.castShadow=true;crowns.castShadow=true;crowns.receiveShadow=true;scene.add(trunks,crowns);
  return {update:time=>{waterTime.value=time;}};
}
