import * as THREE from 'three';
import {surface} from './surface-textures.mjs';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {clone as cloneSkeleton} from 'three/addons/utils/SkeletonUtils.js';

const SCALE=1/50,models={sentinel:'warrior',arcanist:'wizard',ranger:'ranger',bulwark:'monk',shade:'rogue',oracle:'cleric'};
const colorFor=team=>team===0?0x48e2dd:team===1?0xff775a:0xb688ed;
const v3=(x,y,height=0)=>new THREE.Vector3(x*SCALE,height,y*SCALE);
const matte=color=>new THREE.MeshStandardMaterial({color,roughness:.82});
const shared={stone:matte(0x718480),darkStone:matte(0x384e52),gold:matte(0xc5aa66),wood:matte(0x5e4934)};
function mesh(geometry,material,x=0,y=0,z=0){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;return m;}
function cylinder(radius,height,material,y=height/2){return mesh(new THREE.CylinderGeometry(radius,radius,height,8),material,0,y,0);}
function structure(type,team){const group=new THREE.Group(),tint=colorFor(team),gem=new THREE.MeshStandardMaterial({color:tint,emissive:tint,emissiveIntensity:.7,metalness:.25,roughness:.22});
  const base=type==='base';group.add(cylinder(base?1.35:.63,.18,shared.darkStone));group.add(cylinder(base?1.16:.54,.18,shared.gold,.26));group.add(cylinder(base?.9:.42,base?.35:1.5,shared.stone,base?.65:1));
  const crystal=mesh(new THREE.OctahedronGeometry(base?.42:.38),gem,0,base?.95:2,0);crystal.scale.y=1.5;group.add(crystal);group.userData.crystal=crystal;
  for(let i=0;i<(base?6:4);i++){const a=i*Math.PI*2/(base?6:4),r=base?1:.47,pillar=cylinder(.11,base?.35:1.6,shared.darkStone);pillar.position.set(Math.cos(a)*r,base?.65:1,Math.sin(a)*r);group.add(pillar);const cap=mesh(new THREE.ConeGeometry(.18,.32,4),gem,pillar.position.x,pillar.position.y+(base?.2:.9),pillar.position.z);group.add(cap);}
  return group;
}
function minion(team){const group=new THREE.Group(),metal=matte(team===0?0x78acb4:0xc58872);group.add(mesh(new THREE.CapsuleGeometry(.15,.28,3,6),metal,0,.34,0));group.add(mesh(new THREE.SphereGeometry(.14,6,4),shared.gold,0,.67,0));group.add(mesh(new THREE.BoxGeometry(.035,.36,.07),shared.stone,.22,.35,0));return group;}
function monster(camp){const group=new THREE.Group(),boss=camp==='boss',material=new THREE.MeshStandardMaterial({color:boss?0x7e5bab:0x547c93,roughness:.6,metalness:.15});group.add(mesh(new THREE.IcosahedronGeometry(boss?.8:.45,1),material,0,boss?.75:.4,0));for(let i=0;i<4;i++){const leg=mesh(new THREE.ConeGeometry(boss?.23:.12,boss?.7:.35,5),shared.darkStone,Math.cos(i*Math.PI/2)*(boss?.65:.38),.2,Math.sin(i*Math.PI/2)*(boss?.65:.38));leg.rotation.z=Math.PI;group.add(leg);}const crown=mesh(new THREE.OctahedronGeometry(boss?.45:.28),new THREE.MeshStandardMaterial({color:boss?0xf2c477:0xc592ff,emissive:boss?0xac6b22:0x7b36ad,emissiveIntensity:.7}),0,boss?1.55:.98,0);crown.scale.y=1.3;group.add(crown);group.userData.crystal=crown;return group;}
function makeRing(radius,color,opacity=.6){const ring=mesh(new THREE.RingGeometry(radius*.95,radius,64),new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.y=.065;ring.castShadow=false;return ring;}
function distanceToRoutes(x,y,routes){let best=Infinity;for(const route of routes)for(let i=1;i<route.length;i++){const a=route[i-1],b=route[i],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy)));best=Math.min(best,Math.hypot(x-a[0]-dx*t,y-a[1]-dy*t));}return best;}
function terrain(scene,routes,obstacles,bushes){const grass=new THREE.Mesh(new THREE.PlaneGeometry(90,70),new THREE.MeshStandardMaterial({map:surface("grass"),color:0xb5c4aa,roughness:1}));grass.rotation.x=-Math.PI/2;grass.position.set(15,-.03,10);grass.receiveShadow=true;scene.add(grass);
  for(const route of routes){const curve=new THREE.CatmullRomCurve3(route.map(p=>v3(p[0],p[1],.04)),false,'catmullrom',.05);const road=mesh(new THREE.TubeGeometry(curve,90,.76,8,false),new THREE.MeshStandardMaterial({map:surface("stone"),color:0xb0b4a3,roughness:1}));road.scale.y=.04;road.position.y=.055;road.castShadow=false;scene.add(road);const edge=mesh(new THREE.TubeGeometry(curve,90,.91,8,false),matte(0x63725b));edge.scale.y=.03;edge.position.y=.02;edge.castShadow=false;scene.add(edge);}
  const riverCurve=new THREE.CatmullRomCurve3([v3(620,-200),v3(740,240),v3(730,520),v3(870,760),v3(950,1200)]);const river=mesh(new THREE.TubeGeometry(riverCurve,80,1.12,12,false),new THREE.MeshStandardMaterial({color:0x2d858f,roughness:.27,metalness:.35}));river.scale.y=.025;river.position.y=.025;river.castShadow=false;scene.add(river);
  const treePoints=[];let seed=9284;const rand=()=>{seed=(seed*16807)%2147483647;return (seed-1)/2147483646;};for(let i=0;i<330;i++){const x=rand()*2100-300,y=rand()*1500-250;if(distanceToRoutes(x,y,routes)<105||Math.hypot(x-120,y-840)<190||Math.hypot(x-1380,y-160)<190||Math.abs(x-(680+y*.16))<80||[[640,330],[860,670],[750,500]].some(p=>Math.hypot(x-p[0],y-p[1])<105))continue;treePoints.push({x,y,s:.65+rand()*.65});}
  const trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.055,.11,.8,5),shared.wood,treePoints.length),leaves=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(.66,1),matte(0x255749),treePoints.length),crowns=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(.53,1),matte(0x49694a),treePoints.length);const dummy=new THREE.Object3D();treePoints.forEach((p,i)=>{dummy.position.copy(v3(p.x,p.y,.4*p.s));dummy.scale.setScalar(p.s);dummy.rotation.set(0,p.x,0);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);dummy.position.y=1.2*p.s;dummy.updateMatrix();leaves.setMatrixAt(i,dummy.matrix);dummy.position.y=1.6*p.s;dummy.position.x+=.2*p.s;dummy.scale.set(p.s,p.s*.78,p.s);dummy.updateMatrix();crowns.setMatrixAt(i,dummy.matrix);});scene.add(trunks,leaves,crowns);
  for(const o of obstacles){const rock=mesh(new THREE.DodecahedronGeometry(o.radius*SCALE*.92,1),shared.stone);rock.position.copy(v3(o.x,o.y,.25));rock.scale.set(1,.45,1);rock.rotation.set(.2,o.x,.1);scene.add(rock);const moss=mesh(new THREE.IcosahedronGeometry(o.radius*SCALE*.78,0),matte(0x547049));moss.position.copy(v3(o.x,o.y,o.radius*SCALE*.56));moss.scale.y=.25;scene.add(moss);}
  for(const b of bushes)for(let i=0;i<12;i++){const shrub=mesh(new THREE.IcosahedronGeometry(.24+rand()*.13,0),matte(i%2?0x77954f:0x5b8245));shrub.position.copy(v3(b.x+(rand()-.5)*b.w,b.y+(rand()-.5)*b.h,.25));shrub.scale.y=.8;shrub.castShadow=false;scene.add(shrub);}
}
export function create(options){const {canvas,previewCanvas,routes,obstacles=[],bushes=[],onStatus}=options;
  const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.4));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x243f36);scene.fog=new THREE.Fog(0x344c41,25,65);scene.add(new THREE.HemisphereLight(0xbde5eb,0x3a493a,1.9));const sun=new THREE.DirectionalLight(0xffecc9,2.3);sun.position.set(5,20,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-23;sun.shadow.camera.right=23;sun.shadow.camera.top=20;sun.shadow.camera.bottom=-20;sun.shadow.normalBias=.06;scene.add(sun);terrain(scene,routes,obstacles,bushes);
  const camera=new THREE.OrthographicCamera(-10,10,6,-6,.1,100),focus=new THREE.Vector3(15,0,10),raycaster=new THREE.Raycaster(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),intersection=new THREE.Vector3(),entities=new Map(),templates=new Map(),loader=new GLTFLoader();let last=0,previousTime=-1,previousPlayer=null,width=0,height=0,low=false,preview=null;
  const previewRenderer=new THREE.WebGLRenderer({canvas:previewCanvas,alpha:true,antialias:true});previewRenderer.setPixelRatio(Math.min(devicePixelRatio||1,1.4));previewRenderer.outputColorSpace=THREE.SRGBColorSpace;previewRenderer.toneMapping=THREE.ACESFilmicToneMapping;previewRenderer.toneMappingExposure=1.25;const previewScene=new THREE.Scene();previewScene.add(new THREE.HemisphereLight(0xd9efff,0x393427,2.5));const previewLight=new THREE.DirectionalLight(0xffeedc,3);previewLight.position.set(-3,6,4);previewScene.add(previewLight);const previewCamera=new THREE.PerspectiveCamera(35,1,.1,20);previewCamera.position.set(0,1.5,4.5);previewCamera.lookAt(0,.95,0);let previewAngle=0,previewId=null,portraitDone=new Set(),previewWidth=0,previewHeight=0;
  function character(id){const template=templates.get(id);if(!template)return {group:minion(0),mixer:null};const object=cloneSkeleton(template.scene),bounds=new THREE.Box3().setFromObject(object),size=bounds.getSize(new THREE.Vector3()),factor=(id==='bulwark'?1.85:1.65)/size.y;object.scale.multiplyScalar(factor);object.position.y=-bounds.min.y*factor;object.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;}});const group=new THREE.Group();group.add(object);const mixer=new THREE.AnimationMixer(object),actions={};for(const clip of template.animations)actions[clip.name]=mixer.clipAction(clip);return {group,mixer,actions,current:null};}
  function play(node,name,once=false,speed=1){const action=node.actions?.[name];if(!action||node.current===name&&!once)return;node.active?.fadeOut(.1);action.reset().setEffectiveTimeScale(speed).setEffectiveWeight(1);action.setLoop(once?THREE.LoopOnce:THREE.LoopRepeat,once?1:Infinity);action.clampWhenFinished=once;action.fadeIn(.1).play();node.active=action;node.current=name;}
  const loading=Promise.all(Object.entries(models).map(async([id,file])=>{const gltf=await loader.loadAsync('assets/models/'+file+'.glb');templates.set(id,gltf);canvas.dataset.models=String(templates.size);onStatus?.(templates.size,6);})).then(()=>{canvas.dataset.ready='true';return true;}).catch(e=>{canvas.dataset.assetError=e.message;onStatus?.(-1,6);return false;});canvas.dataset.renderer='webgl2';
  function rebuild(e){const node=e.type==='hero'?character(e.def.id):{group:e.type==='tower'||e.type==='base'?structure(e.type,e.team):e.type==='monster'?monster(e.camp):minion(e.team),mixer:null};node.kind=e.type+':'+(e.def?.id||e.camp||e.team);node.ring=makeRing((e.type==='hero'?e.radius+4:e.radius)*SCALE,colorFor(e.team),e.player?.85:.42);node.group.add(node.ring);node.group.position.copy(v3(e.x,e.y));node.lastX=e.x;node.lastY=e.y;node.lastAttack=-1;scene.add(node.group);entities.set(e.id,node);return node;}
  function disposeNode(n){n.mixer?.stopAllAction();n.mixer?.uncacheRoot(n.mixer.getRoot());scene.remove(n.group);if(n.mixer){for(const owned of [n.ring,n.shield]){owned?.geometry.dispose();owned?.material.dispose();}}else n.group.traverse(m=>{if(m.isMesh){m.geometry?.dispose();if(!Object.values(shared).includes(m.material))m.material?.dispose();}});}
  const aimRing=makeRing(1,0x96fff0,.7),castRing=makeRing(1,0xb5a1ff,.65),selectionRing=makeRing(1,0x89efec,.17);scene.add(aimRing,castRing,selectionRing);const aimLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xb6fff2,transparent:true,opacity:.8}));scene.add(aimLine);const fxRoot=new THREE.Group();scene.add(fxRoot);const cachedFx=new Map();
  function project(x,y,h=0){const p=v3(x,y,h).project(camera);return {x:(p.x+1)*width/2,y:(1-p.y)*height/2};}
  function unproject(x,y){raycaster.setFromCamera(new THREE.Vector2(x/width*2-1,1-y/height*2),camera);return raycaster.ray.intersectPlane(plane,intersection)?{x:intersection.x/SCALE,y:intersection.z/SCALE}:{x:750,y:500};}
  function render(state,{follow=true,aim=null,visible=()=>true,aimInfo=null,selected='sentinel'}={}){const now=performance.now()/1000,dt=Math.min(.05,now-last||0);last=now;const rect=canvas.getBoundingClientRect();if(rect.width!==width||rect.height!==height){width=rect.width;height=rect.height;renderer.setSize(width,height,false);}if(!width||!height)return;
    const target=state&&follow?v3(state.player.x,state.player.y):v3(750,500);if(state&&(state.player.id!==previousPlayer||previousTime<0||state.time<previousTime))focus.copy(target);else focus.lerp(target,state?.paused?1:1-Math.exp(-14*dt));previousTime=state?.time??-1;previousPlayer=state?.player.id??null;const span=state&&follow?(height<500?9.3:11):23;camera.left=-span*width/height/2;camera.right=-camera.left;camera.top=span/2;camera.bottom=-span/2;camera.position.copy(focus).add(new THREE.Vector3(0,14,11));camera.lookAt(focus);camera.updateProjectionMatrix();camera.updateMatrixWorld();sun.target.position.copy(focus);scene.add(sun.target);
    const live=new Set();for(const e of state?.entities||[]){live.add(e.id);let n=entities.get(e.id);if(!n||n.kind!==e.type+':'+(e.def?.id||e.camp||e.team)||e.type==='hero'&&!n.mixer&&templates.has(e.def.id)){if(n)disposeNode(n);n=rebuild(e);}const justDied=e.dead&&!n.dead;n.dead=e.dead;if(justDied&&e.type==='hero')play(n,'Death',true);n.group.visible=visible(e)&&(!e.dead||e.type==='hero'&&e.respawn>4);if(!n.group.visible)continue;const dx=e.x-n.lastX,dy=e.y-n.lastY,moving=Math.hypot(dx,dy)>.03;if(Math.hypot(dx,dy)>105){n.dash=.18;play(n,n.actions?.Roll?'Roll':'Run',true,1.4);}const facing=e.facing;if(facing&&(!moving||now<(n.actionEnd||0)))n.heading=Math.atan2(facing.x,facing.y);else if(moving)n.heading=Math.atan2(dx,dy);if(n.heading!==undefined){const angle=Math.atan2(Math.sin(n.heading-n.group.rotation.y),Math.cos(n.heading-n.group.rotation.y));n.group.rotation.y+=angle*(1-Math.exp(-20*dt));}n.lastX=e.x;n.lastY=e.y;if(n.dash>0){n.dash=Math.max(0,n.dash-dt);n.group.position.lerp(v3(e.x,e.y),1-Math.exp(-32*dt));}else n.group.position.copy(v3(e.x,e.y));n.group.position.y=0;
      if(!e.dead&&e.actionAt!==undefined&&e.actionAt!==n.lastAttack){n.lastAttack=e.actionAt;const names=e.actionAnim==='dash'?['Roll','Run_Weapon','Run']:e.actionAnim==='spell'?['Spell1','Staff_Attack','Punch']:e.actionAnim==='ultimate'?['Spell2','Spell1','Dagger_Attack2','Sword_Attack2','Attack2']:['Sword_Attack','Dagger_Attack','Bow_Shoot','Attack','Staff_Attack','Punch'];play(n,names.find(a=>n.actions?.[a]),true,e.rage>0?1.6:1.2);n.actionEnd=now+(e.actionAnim==='dash'?.3:e.actionAnim==='ultimate'?1:.4);}else if(!e.dead&&now>=(n.actionEnd||0)&&!n.dash){const names=moving?['Run_Weapon','Run_Holding','Run','Walk']:['Idle_Weapon','Idle_Attacking','Attacking_Idle','Idle'];play(n,names.find(a=>n.actions?.[a]),false,moving?Math.max(.75,Math.min(1.5,(e.speed||190)/190)):1);}if(!state?.paused)n.mixer?.update(dt);if(e.type==='minion')n.group.position.y=moving?Math.abs(Math.sin(now*12+e.id))*.06:0;if(n.group.userData.crystal){n.group.userData.crystal.rotation.y=now*.6;n.group.userData.crystal.position.y+=Math.sin(now*2+e.id)*.002;}
      n.ring.material.opacity=e.player?.85:e.type==='hero'?.4:.18;n.ring.material.color.setHex(colorFor(e.team));if(e.shield>0&&!n.shield){n.shield=mesh(new THREE.SphereGeometry(.85,16,10),new THREE.MeshBasicMaterial({color:0x92defe,transparent:true,opacity:.18,depthWrite:false}),0,.8,0);n.group.add(n.shield);}if(n.shield)n.shield.visible=e.shield>0;
    }for(const[id,n]of entities)if(!live.has(id)){disposeNode(n);entities.delete(id);}
    selectionRing.visible=!!state&&!state.player.dead;aimRing.visible=!!aim&&!!state;aimLine.visible=!!aim&&!!state;if(state){selectionRing.position.copy(v3(state.player.x,state.player.y,.06));selectionRing.scale.setScalar(state.player.range*SCALE);if(aim){const location=aimInfo?.mode==='area'?aim.aim:state.player,rad=(aimInfo?.radius||170)*SCALE;aimRing.position.copy(v3(location.x,location.y,.09));aimRing.scale.setScalar(rad);aimRing.material.color.setHex(aim.cancelled?0xff7157:0x96fff0);aimLine.geometry.dispose();aimLine.geometry=new THREE.BufferGeometry().setFromPoints([v3(state.player.x,state.player.y,.1),v3(aim.aim.x,aim.aim.y,.1)]);aimLine.visible=aimInfo?.mode==='direction';}}
    const liveFx=new Set();for(const f of state?.effects||[]){if(!['ring','shot','telegraph','slash','bolt'].includes(f.type))continue;const key=f.fxId??`${f.type}:${f.x}:${f.y}:${f.tx}:${f.radius}:${f.max}`;liveFx.add(key);let object=cachedFx.get(key);if(!object){if(f.type==='slash'){const angle=Math.atan2(-(f.ty-f.y),f.tx-f.x),radius=f.radius*SCALE;object=mesh(new THREE.RingGeometry(radius*.6,radius,32,1,angle-.58,1.16),new THREE.MeshBasicMaterial({color:f.color,side:THREE.DoubleSide,transparent:true,opacity:.85,depthWrite:false}));object.rotation.x=-Math.PI/2;object.castShadow=false;}else if(f.type==='bolt'){object=mesh(new THREE.SphereGeometry(.075,8,6),new THREE.MeshBasicMaterial({color:f.color,transparent:true}));object.castShadow=false;}else if(f.type==='shot'){const geometry=new THREE.BufferGeometry().setFromPoints([v3(f.x,f.y,.55),v3(f.tx,f.ty,.55)]);object=new THREE.Line(geometry,new THREE.LineBasicMaterial({color:f.color,transparent:true}));}else object=makeRing(f.radius*SCALE,f.color,.7);fxRoot.add(object);cachedFx.set(key,object);}const progress=1-f.life/f.max;object.material.opacity=f.type==='slash'?Math.sin(progress*Math.PI)*.8:Math.max(.1,f.life/f.max);if(f.type==='bolt'){object.position.copy(v3(f.x+(f.tx-f.x)*progress,f.y+(f.ty-f.y)*progress,.8));}else if(f.type!=='shot'){object.position.copy(v3(f.x,f.y,.1));object.scale.setScalar(f.type==='telegraph'?1:1+(1-f.life/f.max)*.18);}}for(const[key,obj]of cachedFx)if(!liveFx.has(key)){fxRoot.remove(obj);obj.geometry.dispose();obj.material.dispose();cachedFx.delete(key);}castRing.visible=false;
    renderer.render(scene,camera);canvas.dataset.drawCalls=String(renderer.info.render.calls);canvas.dataset.triangles=String(renderer.info.render.triangles);
    if(!state){for(const card of options.portraitCanvases||[]){const id=card.dataset.model;if(portraitDone.has(id)||!templates.has(id))continue;const portrait=character(id);portrait.group.rotation.y=.2;play(portrait,["Idle_Weapon","Idle_Attacking","Idle"].find(a=>portrait.actions[a]));portrait.mixer.update(.15);if(preview)previewScene.remove(preview.group);previewScene.add(portrait.group);previewRenderer.setSize(card.width,card.height,false);previewWidth=0;previewHeight=0;previewCamera.position.set(0,1.5,2.7);previewCamera.lookAt(0,1.15,0);previewCamera.aspect=card.width/card.height;previewCamera.updateProjectionMatrix();previewRenderer.render(previewScene,previewCamera);card.getContext("2d").drawImage(previewCanvas,0,0,card.width,card.height);previewCamera.position.set(0,1.5,4.5);previewCamera.lookAt(0,.95,0);card.dataset.ready="true";portraitDone.add(id);previewScene.remove(portrait.group);portrait.mixer.stopAllAction();portrait.mixer.uncacheRoot(portrait.mixer.getRoot());if(preview)previewScene.add(preview.group);}if(previewId!==selected&&templates.has(selected)){if(preview){previewScene.remove(preview.group);preview.mixer.stopAllAction();preview.mixer.uncacheRoot(preview.mixer.getRoot());}preview=character(selected);previewId=selected;preview.group.rotation.y=previewAngle;previewScene.add(preview.group);play(preview,['Idle_Weapon','Idle_Attacking','Idle'].find(a=>preview.actions[a]));}const pr=previewCanvas.getBoundingClientRect();if(pr.width&&pr.height){if(previewWidth!==pr.width||previewHeight!==pr.height){previewWidth=pr.width;previewHeight=pr.height;previewRenderer.setSize(pr.width,pr.height,false);previewCamera.aspect=pr.width/pr.height;previewCamera.updateProjectionMatrix();}if(preview){preview.group.rotation.y=previewAngle;preview.mixer.update(dt);previewCanvas.dataset.hero=previewId;}previewRenderer.render(previewScene,previewCamera);}}
  }
  return {render,project,unproject,loading,turnPreview:angle=>{previewAngle+=angle;},quality:()=>{low=!low;renderer.setPixelRatio(low?1:Math.min(devicePixelRatio||1,1.4));renderer.shadowMap.enabled=!low;return low?'ประหยัด':'ปกติ';},stats:()=>({models:templates.size,entities:entities.size,renderer:'WebGL2'}),dispose:()=>{for(const n of entities.values())disposeNode(n);renderer.dispose();previewRenderer.dispose();}};
}
