const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'dist'),port=Number(process.env.PORT)||4173;
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.webp':'image/webp','.glb':'model/gltf-binary','.txt':'text/plain; charset=utf-8'};
async function start(){fs.mkdirSync(path.join(__dirname,'.sites-runtime'),{recursive:true});const DB=require('./server/local-db.cjs').createDb(path.join(__dirname,'.sites-runtime/rooms.sqlite'));const worker=(await import('./server/worker.mjs')).default;
http.createServer(async(req,res)=>{let pathname;try{pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);}catch{res.writeHead(400);res.end('Bad request');return;}
if(pathname.startsWith('/api/')){try{const chunks=[];let size=0;const limit=pathname.startsWith('/api/lesson-banks')?1100000:pathname.startsWith('/api/classes/')?512000:140000;for await(const chunk of req){size+=chunk.length;if(size>limit){res.writeHead(413);res.end('{}');return;}chunks.push(chunk);}const request=new Request('http://'+req.headers.host+req.url,{method:req.method,headers:req.headers,body:['GET','HEAD'].includes(req.method)?undefined:Buffer.concat(chunks)});const response=await worker.fetch(request,{DB},{});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch(e){console.error(e.message);res.writeHead(500);res.end('{}');}return;}
const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)||pathname.startsWith('/server/')||pathname.startsWith('/.openai/')){res.writeHead(403);res.end('Forbidden');return;}
fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','cache-control':'no-store'});res.end(err?'Not found':data);});
}).listen(port,'127.0.0.1',()=>console.log(`Local: http://127.0.0.1:${port}`));}
start().catch(e=>{console.error(e);process.exitCode=1;});
