const assert=require('node:assert/strict'),{run}=require('./smoke.cjs');
function fresh(id){run(`lobby();chooseHero('${id}');startGame();game.wave=999;game.entities=game.entities.filter(e=>e.type==='hero');game.player.x=700;game.player.y=500;game.entities.filter(e=>!e.player).forEach(e=>{e.remoteHuman=true;e.x=1400;e.y=900;});`);}
function tick(seconds){run(`for(let i=0;i<${Math.ceil(seconds/.05)};i++)update(.05)`);}
function check(s,m){assert.ok(run(s),m);}
function target(x=850,y=500){run(`globalThis.victim=game.entities.find(e=>e.team===1);victim.x=${x};victim.y=${y};victim.maxHp=victim.hp=10000;`);}
check('HEROES.length===16&&new Set(HEROES.map(h=>h.id)).size===16','sixteen unique playable heroes');
fresh('stuart');target();run('useSkill("w");const protectedHp=game.player.hp;damage(game.player,200,victim)');check('game.player.hp===protectedHp','Stuart defense blocks damage');tick(1.4);run('damage(game.player,100,victim)');check('game.player.hp<protectedHp','defense expires');run('useSkill("e",game.player,{x:850,y:500})');tick(.4);check('game.player.x<700&&victim.stun>0&&victim.hp<10000','Stuart retreat and stun projectile');
fresh('capheny');target();run('const gunRange=game.player.range;useSkill("q");strike(game.player,victim);');check('game.player.cannonMode&&game.player.range===gunRange+55&&game.strikes[0].splash===80','Capheny cannon mode changes range and splash');tick(2.1);run('useSkill("q")');check('!game.player.cannonMode&&game.player.range===gunRange','toggle restores range without accumulating bonus');run('useSkill("e",game.player,{x:850,y:500})');tick(.35);check('victim.hp<10000&&game.championEvents.length>0','fan fires across multiple ticks');run('stun(game.player,1)');tick(.05);check('game.player.channel===0&&game.championEvents.length===0','stun cancels remaining fan shots');
fresh('maloch');target(800);run('game.player.hp=500;useSkill("q",game.player,{x:800,y:500});useSkill("w");');check('victim.hp<10000&&game.player.hp>500&&game.player.shield>120&&victim.slow>0','Maloch slash heals and drain shields');run('useSkill("e",game.player,{x:800,y:500})');tick(.5);check('victim.stun>0&&game.player.x===800','Maloch landing stuns');
fresh('ignis');target();run('useSkill("q",game.player,{x:850,y:500})');tick(.25);check('victim.fireMark?.source===game.player.id','Ignis fire marks enemy');run('useSkill("w",game.player,{x:850,y:500})');tick(.4);check('victim.stun>0&&!victim.fireMark','rain consumes mark to stun');
fresh('mortos');target(775);run('useSkill("q");strike(game.player,victim)');tick(.25);check('victim.silence>0&&!useSkill("q",victim)','Mortos enhanced strike prevents enemy spells');run('useSkill("w")');check('game.player.spin>0&&game.player.shield>0','Mortos persistent spin and shield');
fresh('taara');target(775);run('game.player.hp=400;const taaraHp=game.player.hp;useSkill("e")');tick(1);check('game.player.hp>taaraHp+game.player.maxHp*.05','Taara ultimate heals over time');run('useSkill("w")');tick(.35);check('victim.hp<9800','hammer resolves both swings');
fresh('elsu');target(520,410);run('game.time=10;game.player.x=700;game.player.y=500;');check('!visibleToTeam(victim,0)','bush conceals distant enemy');run('useSkill("q",game.player,{x:520,y:410})');check('visibleToTeam(victim,0)&&game.wards.length===1','Elsu sensor reveals bush');run('game.player.cd.q=0;useSkill("q",game.player,{x:500,y:400});game.player.cd.q=0;useSkill("q",game.player,{x:500,y:400});game.player.cd.q=0;useSkill("q",game.player,{x:500,y:400})');check('game.wards.length===3','sensor limit removes oldest');target(1000);run('useSkill("w",game.player,{x:1000,y:500})');check('victim.hp===10000','sniper has aim delay');tick(.8);check('victim.hp<9650&&victim.slow>0','sniper hits aimed long-range target');run('game.time+=46;update(.05)');check('game.wards.length===0','sensors expire');
fresh('hayate');target(850);run('useSkill("q",game.player,{x:850,y:500})');tick(.8);check('victim.hp<9650&&game.championEvents.length===0','six shurikens resolve over time');run('useSkill("e",game.player,{x:850,y:500})');tick(.25);run('const beforeInterrupt=victim.hp;stun(game.player,1)');tick(1);check('victim.hp===beforeInterrupt&&game.casts.length===0','stun interrupts vortex damage');
fresh('flowborn');target(800);run('game.player.hp=500;game.player.cd.w=6;game.player.cd.e=8;useSkill("q")');check('game.player.hp>500&&game.player.flowStacks===5&&game.player.cd.w===3&&game.player.cd.e===4&&victim.x>800','Flow grants charges, heals, reduces cooldowns and pushes');run('game.player.cd.e=0;useSkill("e",game.player,{x:850,y:500})');tick(.25);run('useSkill("e",game.player,{x:950,y:500})');check('game.player.flowUlt===0&&game.player.cd.e>18&&game.player.x===950','second jump consumes recast and starts full cooldown');
fresh('flowborn');run('useSkill("e",game.player,{x:800,y:500})');tick(3.2);check('game.player.flowUlt===0&&game.player.cd.e>15','unused Flow jump expires with cooldown');
fresh('zata');target(900);run('useSkill("e",game.player,{x:780,y:500})');tick(.25);run('useSkill("e",game.player,{x:840,y:500})');tick(.25);run('useSkill("e",game.player,{x:900,y:500})');check('game.player.flight>0&&game.player.invulnerable>0&&game.player.cd.e>22','third Zata dash enters flight');tick(1.8);check('game.player.flight===0&&game.player.invulnerable===0&&victim.hp<10000','flight attacks and protection expire');
for(const id of ['stuart','capheny','maloch','ignis','mortos','taara','elsu','hayate','flowborn','zata']){fresh(id);run('game.player.mana=0');check('!useSkill("q")&&!useSkill("w")&&!useSkill("e")&&Object.values(game.player.cd).every(v=>v===0)',id+' mana gate');run('game.player.mana=400');tick(10);check('game.entities.every(e=>Number.isFinite(e.x)&&Number.isFinite(e.y)&&Number.isFinite(e.hp))',id+' finite simulation');}
console.log('PASS: 10 heroes, damage/CC, mode toggle, timed shots, interruption, marks, sensors, regeneration, recast expiry, flight and mana gates.');
