const assert=require('node:assert/strict'),{run}=require('./smoke.cjs');
function fresh(id){run(`lobby();chooseHero('${id}');startGame();game.wave=999;game.player.x=700;game.player.y=500;game.entities=game.entities.filter(e=>e.type==='hero');game.entities.filter(e=>!e.player).forEach(e=>{e.remoteHuman=true;e.x=1400;e.y=900;});`);}
function check(code,label){assert.ok(run(code),label);}
fresh('shade');run('const p=game.player;useSkill("q",p,{x:1000,y:500});');check('p.x===880&&p.qCombo===1&&p.mana===350','first dash opens second charge');
run('update(.2);useSkill("q",p,{x:1000,y:500});');check('p.x===1060&&p.qCombo===0&&p.cd.q>7&&p.mana<310','second dash consumes charge, mana and shared cooldown');
fresh('shade');run('useSkill("q");for(let i=0;i<65;i++)update(.05);');check('game.player.qCombo===0&&game.player.cd.q>4','unused charge expires without resetting full cooldown');
fresh('arcanist');run('const target=game.entities.find(e=>e.team===1);target.x=950;target.y=500;const hp=target.hp;useSkill("q",game.player,{x:950,y:500});');check('target.hp===hp&&game.casts.length===1','targeted spell has warning before damage');run('for(let i=0;i<8;i++)update(.05);');check('target.hp<hp&&game.casts.length===0','spell damages target at aimed location');
fresh('arcanist');run('const escaping=game.entities.find(e=>e.team===1);escaping.x=900;escaping.y=500;const escapeHp=escaping.hp;useSkill("e",game.player,{x:900,y:500});escaping.x=1400;for(let i=0;i<14;i++)update(.05);');check('escaping.hp===escapeHp','moving outside telegraph avoids delayed spell');
fresh('ranger');run('const creep=entity("minion",1,720,500);game.entities.push(creep);const creepHp=creep.hp;useSkill("q",game.player,{x:1100,y:500});update(.05);');check('creep.hp<creepHp&&game.projectiles.length<3','swept arrow hits small target between frames');
fresh('sentinel');run('game.player.mana=0;const noManaX=game.player.x;');check('!useSkill("w")&&game.player.cd.w===0&&game.player.x===noManaX','insufficient mana consumes neither movement nor cooldown');run('update(.05);');check('game.player.mana>0','mana regenerates');
fresh('shade');run('const prey=game.entities.find(e=>e.team===1);prey.x=880;prey.y=500;const hpPrey=prey.hp;useSkill("e");stun(game.player,2);');check('game.player.stun===0&&game.player.channel>0&&game.casts.length===3','ultimate channel resists stun');run('for(let i=0;i<17;i++)update(.05);');check('prey.hp<hpPrey-250&&prey.stun>0&&game.casts.length===0','ultimate resolves four hits and final stun');
fresh('sentinel');run('const hiddenEnemy=game.entities.find(e=>e.team===1);hiddenEnemy.x=520;hiddenEnemy.y=410;game.time=10;');check('!visibleToTeam(hiddenEnemy,0)','distant enemy hidden in bush');run('hiddenEnemy.lastDamaged=game.time;');check('visibleToTeam(hiddenEnemy,0)','recent damage reveals bush enemy');run('hiddenEnemy.lastDamaged=0;game.player.x=540;game.player.y=400;');check('visibleToTeam(hiddenEnemy,0)','nearby hero reveals bush enemy');
run('game.player.x=420;game.player.y=360;safeLanding(game.player);');check('distance(game.player,OBSTACLES[0])>=OBSTACLES[0].radius+game.player.radius-.001','dash landing outside solid rock');
fresh('sentinel');run('game.player.range=250;const heroTarget=game.entities.find(e=>e.team===1);heroTarget.x=730;heroTarget.y=500;const towerTarget=entity("tower",1,800,500);game.entities.push(towerTarget);$("targetMode").value="tower";');check('attackTarget(game.player)===towerTarget','tower button selects structure before closer hero');
console.log('PASS: dash charges/expiry, delayed aim/dodge, swept projectiles, mana gate/regen, combo channel/stun immunity, bush visibility, rock landing, structure priority.');
