const assert=require('node:assert/strict'),{run}=require('./smoke.cjs');
function fresh(id){run(`lobby();chooseHero('${id}');startGame();game.wave=999;game.player.x=700;game.player.y=500;game.entities=game.entities.filter(e=>e.type==='hero');game.entities.filter(e=>!e.player).forEach(e=>{e.remoteHuman=true;e.x=1400;e.y=900;});`);}
const check=(s,m)=>assert.ok(run(s),m),tick=s=>run(`for(let i=0;i<${Math.ceil(s/.05)};i++)update(.05);`);
fresh('ranger');run('const target=game.entities.find(e=>e.team===1);target.x=1000;target.y=500;const startHp=target.hp;game.player.range=400;strike(game.player,target);');tick(.25);check('target.hp===startHp&&game.projectiles.length===1','normal attack travels after windup');run('target.y=580;const blocker=entity("minion",1,850,530);blocker.remoteHuman=true;game.entities.push(blocker);const blockHp=blocker.hp;');tick(.7);check('target.hp<startHp&&blocker.hp===blockHp','targeted normal shot tracks moving target without striking unrelated minion');
fresh('sentinel');run('const tower=entity("tower",1,800,500,{hp:10000,maxHp:10000,range:205,damage:85,speed:0,radius:25});game.entities.push(tower);damage(tower,100,game.player);const bareDamage=10000-tower.hp;const creep=entity("minion",0,780,550);creep.remoteHuman=true;game.entities.push(creep);damage(tower,100,game.player);');check('bareDamage===40&&tower.hp===9860','tower withstands hero damage until allied wave arrives');run('const defender=game.entities.find(e=>e.team===1&&e.type==="hero");defender.x=810;defender.y=550;damage(defender,1,game.player);const towerHpBefore=game.player.hp;update(.05);');check('tower.aggroTarget===game.player.id&&game.player.hp<towerHpBefore','attacking defender draws tower fire through minion wave');run('const shotHp=game.player.hp;tower.attack=0;update(.05);');check('shotHp-game.player.hp>85','repeated tower hits ramp against the same hero');
fresh('zata');run('const initialMana=game.player.mana;useSkill("e",game.player,{x:780,y:500});');tick(.25);run('const recastMana=game.player.mana;useSkill("e",game.player,{x:840,y:500});');check('game.player.mana===recastMana','Zata recast shares the original mana payment');tick(.25);run('useSkill("e",game.player,{x:900,y:500});');check('game.player.flight>0&&game.player.mana>initialMana-91','entire flight combo costs one ultimate payment');
fresh('flowborn');run('useSkill("e",game.player,{x:800,y:500});');tick(.25);run('const secondJumpMana=game.player.mana;useSkill("e",game.player,{x:900,y:500});');check('game.player.mana===secondJumpMana&&game.player.flowUlt===0','Flowborn second jump shares cost and consumes recast');
fresh('stuart');run('const enemyCaster=game.entities.find(e=>e.team===1);enemyCaster.def=HEROES.find(h=>h.id==="ignis");useSkill("w");const hpBeforeMagic=game.player.hp;damage(game.player,100,enemyCaster);');check('game.player.hp<hpBeforeMagic','Stuart physical dodge does not block magic');
fresh('capheny');run('useSkill("e",game.player,{x:1000,y:500});joystick={x:1,y:0};');tick(.2);check('game.player.channel>0&&game.player.x>700&&game.player.x<725','Capheny can move slowly while barrage channels');run('joystick={x:0,y:0};');
console.log('PASS: traveling targeted attacks, minion protection, turret aggro/escalation, recast economy, damage-type dodge and moving barrage.');
