const assert=require('node:assert/strict'),{run}=require('./smoke.cjs');
const check=(s,m)=>assert.ok(run(s),m);
function fresh(id){run(`lobby();chooseHero('${id}');startGame();game.wave=999;game.entities=game.entities.filter(e=>e.type==='hero');game.player.x=700;game.player.y=500;game.entities.filter(e=>!e.player).forEach(e=>{e.remoteHuman=true;e.x=1400;e.y=900;});globalThis.victim=game.entities.find(e=>e.team===1);victim.x=800;victim.y=500;victim.hp=victim.maxHp=10000;victim.enchant='fury';`);}
const tick=t=>run(`for(let i=0;i<${Math.ceil(t/.05)};i++)update(.05)`);
fresh('ilumia');run('useSkill("q",game.player,{x:800,y:500});useSkill("w")');check('game.player.divineUntil>game.time&&game.player.cd.q===0','two casts reset and empower Q');run('useSkill("q",game.player,{x:800,y:500})');tick(.4);check('victim.hp<10000&&victim.stun>0','empowered light knocks up');
fresh('ilumia');run('victim.x=1200;useSkill("e");victim.x=1000');tick(1);check('victim.hp===10000&&!victim.stun','global strike is dodgeable at original cast location');
fresh('ilumia');run('victim.x=1200;useSkill("e")');tick(1);check('victim.hp<10000&&victim.stun>0','global strike reaches distant hero');
fresh('lauriel');run('game.player.hp=500;useSkill("q",game.player,{x:800,y:500})');tick(.6);check('victim.laurielMarks[game.player.id].stacks===2','light deals two hits and stacks marks');run('useSkill("w",game.player,{x:740,y:500})');tick(.5);check('game.player.hp>500&&victim.slow>0&&game.player.cd.w<5','fourth mark heals, bursts and blink hit refunds cooldown');
fresh('lauriel');run('useSkill("e");game.player.cd.q=6');tick(1);check('game.player.cd.q<4','standing in circle accelerates cooldown');run('game.player.x=1100;game.player.cd.q=6');tick(1);check('game.player.cd.q>4.8','outside circle restores normal cooldown');
fresh('liliana');run('const humanRange=game.player.range,humanSpeed=game.player.speed;useSkill("e",game.player,{x:730,y:500})');check('game.player.foxForm&&game.player.range===humanRange-135&&game.player.speed===humanSpeed+30','fox changes range and speed');run('useSkill("w",game.player,{x:850,y:500})');check('game.player.reikoTarget===victim.id','fox dash enables Reiko only on hit');tick(.25);run('useSkill("w")');tick(.6);check('!game.player.reikoTarget&&victim.hp<9500&&game.player.cd.w>7','Reiko follows target and consumes recast');tick(5);run('useSkill("e",game.player,{x:900,y:500})');check('!game.player.foxForm&&game.player.range===humanRange&&game.player.speed===humanSpeed','return to human restores exact stats');
fresh('liliana');run('useSkill("e",game.player,{x:700,y:510});victim.x=1300;useSkill("w",game.player,{x:850,y:500})');check('!game.player.reikoTarget','missed fox dash cannot unlock homing');
fresh('nakroth');run('useSkill("q",game.player,{x:800,y:500})');check('victim.stun>0&&game.player.jurySecond','first dash knocks up');tick(.25);run('useSkill("q",game.player,{x:900,y:500})');check('!game.player.jurySecond&&game.player.cd.q>8&&game.player.x===900','second dash consumes window');
fresh('nakroth');run('useSkill("q",game.player,{x:800,y:500})');tick(5.2);check('!game.player.jurySecond&&game.player.cd.q>3','unused dash expires into remaining cooldown');run('const beforeBlade=victim.hp;game.player.cd.e=0;useSkill("e",game.player,{x:800,y:500});stun(game.player,1)');check('game.player.stun===0','ultimate blocks crowd control');tick(1.15);check('victim.hp<beforeBlade-370&&victim.stun>0','ultimate resolves four hits and final knockup');
fresh('telannas');run('const originalRange=game.player.range;useSkill("q")');check('game.player.range===originalRange+80','Eagle Eye adds range');tick(3.2);check('game.player.range===originalRange&&!game.player.eagleActive','range bonus expires once');run('useSkill("e",game.player,{x:800,y:500})');check('victim.hp===10000','arrow has windup');tick(.65);check('victim.hp<10000&&victim.stun>0&&victim.x>800','arrow stuns and pushes');
fresh('volkath');run('for(let i=0;i<3;i++)damage(victim,1,game.player);useSkill("q")');check('victim.stun>0&&!victim.doom&&game.player.shield>0','third Doom mark empowers slash and fourth bursts');run('game.player.cd.w=0;useSkill("w",game.player,{x:800,y:500})');tick(.3);check('game.player.clawTarget===victim.id','claw hit creates recast target');run('game.player.cd.w=0;useSkill("w")');check('!game.player.clawTarget&&game.player.x===victim.x&&game.player.cd.w>8','claw recast dashes and closes window');
fresh('volkath');run('game.player.stun=1;useSkill("e")');check('game.player.stun===0&&game.player.mounted>0','mount clears control');tick(.35);run('game.player.hp=50;useSkill("e");damage(game.player,99999,victim)');check('game.player.hp>=1&&!game.player.dead&&game.player.immortal>0','dismount prevents death without awarding a kill');tick(3.6);check('!game.player.immortal&&game.player.hp>game.player.maxHp*.24','immortality expires and heals');
fresh('volkath');run('useSkill("e")');tick(8.2);check('game.player.mounted===0&&game.player.immortal>3&&game.player.cd.e>18','mount auto-dismounts and keeps remaining cooldown');
for(const id of run('LORE_HEROES.map(h=>h.id)')){fresh(id);run('game.player.mana=0');check('!useSkill("q")&&!useSkill("w")&&!useSkill("e")',id+' mana gating');run('game.player.mana=400');tick(20);check('game.entities.every(e=>[e.x,e.y,e.hp,e.mana].every(Number.isFinite))',id+' finite simulation');run('game.paused=true');check('!useSkill("e")',id+' pause gating');}
console.log('PASS: six lore heroes, global telegraphs, marks, dual forms, recasts, CC, circle cooldowns, mortality and mana.');
