const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {run,el}=require('./smoke.cjs');
run('const net={localPause:false,session:null};');
run(fs.readFileSync(path.join(__dirname,'../dist/mobile.js'),'utf8'));
run('startGame();view.width=844;view.height=390;setBattleCamera();');
const roundTrip=run('JSON.stringify(canvasPoint({clientX:projectPoint({x:735,y:417}).x,clientY:projectPoint({x:735,y:417}).y}))');
assert.ok(Math.abs(JSON.parse(roundTrip).x-735)<1e-8&&Math.abs(JSON.parse(roundTrip).y-417)<1e-8,'oblique screen/world input round trip');
assert.ok(run('view.tilt===.65 && Math.abs(projectPoint(game.player).x-844*.48)<1'),'mobile camera follows hero');
run('camera.follow=false;setBattleCamera()');assert.ok(run('view.x>=0&&view.y>=0&&WIDTH*view.scale<=view.width+1&&HEIGHT*view.scale*view.tilt<=view.height+1'),'overview fits projected map');
run('game.player.x=700;game.player.y=500;joystick={x:-1,y:0};useSkill("w",null,{x:910,y:500,manual:true})');assert.ok(run('game.player.x===910'),'manual dash aim overrides joystick');
run('camera.follow=true;view.width=390;view.height=844;camera.ready=false;setBattleCamera();draw();');assert.ok(run('Number.isFinite(view.x)&&Number.isFinite(view.y)&&view.scale>0'),'portrait renderer works');
assert.ok(el('selectedName').textContent.length>0,'hero stage reflects selection');
run('game.player.dead=false;game.paused=false;const attackButton=document.querySelectorAll("[data-action]").find(b=>b.dataset.action==="attack");attackButton.setPointerCapture=()=>{};attackButton.onpointerdown({pointerId:11,preventDefault(){}})');
assert.ok(run('keys.has(" ")'),'holding attack sends continuous attack input');
run('attackButton.onpointercancel()');assert.ok(run('!keys.has(" ")'),'cancelled attack releases continuous input');
run('const dashButton=document.querySelectorAll("[data-action]").find(b=>b.dataset.action==="w");dashButton.setPointerCapture=()=>{};game.player.cd.w=0;const dashStartX=game.player.x;dashButton.onpointerdown({pointerId:12,clientX:100,clientY:100,preventDefault(){}});dashButton.onpointermove({pointerId:12,clientX:135,clientY:100});dashButton.onpointerup({pointerId:12})');
assert.ok(run('game.player.x>dashStartX && !skillAim && game.player.cd.w>0'),'drag-release casts dash and clears preview');
run('game.player.cd.w=0;const cancelX=game.player.x;dashButton.onpointerdown({pointerId:13,clientX:100,clientY:100,preventDefault(){}});dashButton.onpointercancel()');assert.ok(run('game.player.x===cancelX&&game.player.cd.w===0&&!skillAim'),'cancelled skill consumes no cooldown');
console.log('PASS: mobile projection/input alignment, following camera, overview, manual dash direction, portrait renderer, hero presentation, held attack/release, drag skill/cancel.');

run('const mapStartX=game.player.x,mapStartY=game.player.y;let mapConsumed=false;canvas.setPointerCapture=()=>{};canvas.listeners.pointerdown({clientX:80,clientY:80,pointerId:44,preventDefault(){},stopImmediatePropagation(){mapConsumed=true;}});');
assert.ok(run('mapConsumed&&camera.peek&&Number.isFinite(camera.peek.x)&&Number.isFinite(camera.peek.y)'),'minimap press consumes walk and creates camera peek');
run('canvas.listeners.pointermove({clientX:2000,clientY:-100,pointerId:44,stopImmediatePropagation(){}});');
assert.ok(run('camera.peek.x===WIDTH-45&&camera.peek.y===45'),'peek clamps outside map during drag');
run('canvas.listeners.pointerup({pointerId:44});');
assert.ok(run('camera.peek===null&&game.player.x===mapStartX&&game.player.y===mapStartY'),'release returns camera and never moves hero');
console.log('PASS: minimap drag pans without walk commands, bounds clamp, release returns to hero.');
