const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
async function main(){const worker=(await import('../server/worker.mjs')).default,DB=require('../server/local-db.cjs').createDb();const api=async(route,method='GET',data,token)=>{const headers={'content-type':'application/json'};if(token)headers.authorization='Bearer '+token;const response=await worker.fetch(new Request('https://arena.test/api/'+route,{method,headers,body:method==='GET'?undefined:JSON.stringify(data)}),{DB},{});return {status:response.status,data:await response.json()};};
const config={name:'Host',team:0,position:'off',hero:'sentinel',rune:'power',enchant:'guard'};const created=await api('rooms','POST',config);assert.equal(created.status,201);const host=created.data;let joined=await api(`rooms/${host.code}/join`,'POST',{...config,name:'Guest',team:1,position:'carry',hero:'ranger'});assert.equal(joined.status,201);const guest=joined.data;
assert.equal((await api(`rooms/${host.code}/join`,'POST',{...config,name:'Collision'})).status,409);assert.equal((await api(`rooms/${host.code}`,'GET')).status,401);let lobby=await api(`rooms/${host.code}`,'GET',undefined,host.token);assert.equal(lobby.data.members.length,2);assert.ok(!JSON.stringify(lobby.data).includes(host.token));assert.ok(!JSON.stringify(lobby.data).includes('host_token'));assert.ok(!JSON.stringify(lobby.data.members).includes('"token"'));
const {sandbox,run}=require('./smoke.cjs');sandbox.setInterval=()=>0;sandbox.AbortSignal=AbortSignal;sandbox.navigator={clipboard:{writeText:async()=>{}}};sandbox.fetch=async(url,options)=>worker.fetch(new Request('https://arena.test'+url,{...options}),{DB},{});vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/network.js'),'utf8'),sandbox);sandbox.roomSession=host;sandbox.roomMembers=lobby.data.members;
run('net.session=roomSession;net.mode="online";originals.start();configureRoster(roomMembers)');assert.equal(run('game.entities.filter(e=>e.remoteHuman).length'),1);assert.equal(run('game.entities.filter(e=>e.type==="hero").length'),10);const snapshot=JSON.parse(run('JSON.stringify(serializeMatch())'));
assert.equal((await api(`rooms/${host.code}/start`,'POST',{state:snapshot},guest.token)).status,403);assert.equal((await api(`rooms/${host.code}/start`,'POST',{state:snapshot},host.token)).status,200);assert.equal((await api(`rooms/${host.code}/join`,'POST',{...config,position:'mid'})).status,409);
await api(`rooms/${host.code}/input`,'POST',{seq:1,move:{x:-1,y:0},aim:{x:750,y:500},attack:false,commands:[{id:1,kind:'buy',item:'blade'}]},guest.token);lobby=await api(`rooms/${host.code}`,'GET',undefined,host.token);sandbox.receivedMembers=lobby.data.members;run('applyRemoteInputs(receivedMembers);const remote=game.entities.find(e=>e.remoteHuman);const originalX=remote.x;for(let i=0;i<5;i++)originals.update(.05)');assert.ok(run('remote.x<originalX'));assert.equal(run('remote.inventory.length'),1);run('applyRemoteInputs(receivedMembers)');assert.equal(run('remote.inventory.length'),1,'repeated commands execute once');
await api(`rooms/${host.code}/input`,'POST',{seq:0,move:{x:1,y:0},commands:[]},guest.token);lobby=await api(`rooms/${host.code}`,'GET',undefined,host.token);assert.equal(lobby.data.members.find(m=>m.id===guest.playerId).seq,1,'old input cannot overwrite new input');assert.equal((await api(`rooms/${host.code}/input`,'POST',{seq:2,move:{x:9,y:0},commands:[]},guest.token)).status,400);
const updated=JSON.parse(run('JSON.stringify(serializeMatch())'));assert.equal((await api(`rooms/${host.code}/state`,'POST',{state:updated},host.token)).status,200);const read=await api(`rooms/${host.code}`,'GET',undefined,guest.token);assert.ok(read.data.state.entities.some(e=>e.clientId===guest.playerId&&e.inventory.length===1));assert.ok(read.data.members.every(m=>m.input===undefined));assert.equal(read.data.state.ack[guest.playerId],1);
await api(`rooms/${host.code}/leave`,'POST',{},guest.token);assert.equal((await api(`rooms/${host.code}`,'GET',undefined,guest.token)).status,401);await api(`rooms/${host.code}/leave`,'POST',{},host.token);assert.equal((await api(`rooms/${host.code}/join`,'POST',{...config,position:'mid'})).status,409);DB.close();console.log('PASS: online two-client room lifecycle, roster, host authority, token isolation, slot collision, input validation/order, movement, item command deduplication, shared state/ack, leave.');}
main().catch(e=>{console.error(e);process.exitCode=1;});
