const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
async function main(){const worker=(await import('../server/worker.mjs')).default,DB=require('../server/local-db.cjs').createDb();const api=async(route,method='GET',data,token)=>{const headers={'content-type':'application/json'};if(token)headers.authorization='Bearer '+token;const response=await worker.fetch(new Request('https://arena.test/api/'+route,{method,headers,body:method==='GET'?undefined:JSON.stringify(data)}),{DB},{});return {status:response.status,data:await response.json()};};
const config={name:'Host',team:0,position:'off',hero:'sentinel',rune:'power',enchant:'guard'};const created=await api('rooms','POST',config);assert.equal(created.status,201);const host=created.data;let joined=await api(`rooms/${host.code}/join`,'POST',{...config,name:'Guest',team:1,position:'carry',hero:'ranger'});assert.equal(joined.status,201);const guest=joined.data;
assert.equal((await api(`rooms/${host.code}/join`,'POST',{...config,name:'Collision'})).status,409);assert.equal((await api(`rooms/${host.code}`,'GET')).status,401);let lobby=await api(`rooms/${host.code}`,'GET',undefined,host.token);assert.equal(lobby.data.members.length,2);assert.ok(!JSON.stringify(lobby.data).includes(host.token));assert.ok(!JSON.stringify(lobby.data).includes('host_token'));assert.ok(!JSON.stringify(lobby.data.members).includes('"token"'));
const {sandbox,run}=require('./smoke.cjs');sandbox.setInterval=()=>0;sandbox.AbortSignal=AbortSignal;sandbox.navigator={clipboard:{writeText:async()=>{}}};sandbox.fetch=async(url,options)=>worker.fetch(new Request('https://arena.test'+url,{...options}),{DB},{});vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/network.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/mobile.js'),'utf8'),sandbox);sandbox.roomSession=host;sandbox.roomMembers=lobby.data.members;
run('net.session=roomSession;net.mode="online";originals.start();configureRoster(roomMembers)');assert.equal(run('game.entities.filter(e=>e.remoteHuman).length'),1);assert.equal(run('game.entities.filter(e=>e.type==="hero").length'),10);const snapshot=JSON.parse(run('JSON.stringify(serializeMatch())'));
assert.equal((await api(`rooms/${host.code}/start`,'POST',{state:snapshot},guest.token)).status,403);assert.equal((await api(`rooms/${host.code}/start`,'POST',{state:snapshot},host.token)).status,200);assert.equal((await api(`rooms/${host.code}/join`,'POST',{...config,position:'mid'})).status,409);
await api(`rooms/${host.code}/input`,'POST',{seq:1,move:{x:-1,y:0},aim:{x:750,y:500},attack:false,commands:[{id:1,kind:'buy',item:'blade'}]},guest.token);lobby=await api(`rooms/${host.code}`,'GET',undefined,host.token);sandbox.receivedMembers=lobby.data.members;run('applyRemoteInputs(receivedMembers);const remote=game.entities.find(e=>e.remoteHuman);const originalX=remote.x;for(let i=0;i<5;i++)originals.update(.05)');assert.ok(run('remote.x<originalX'));assert.equal(run('remote.inventory.length'),1);run('applyRemoteInputs(receivedMembers)');assert.equal(run('remote.inventory.length'),1,'repeated commands execute once');
await api(`rooms/${host.code}/input`,'POST',{seq:0,move:{x:1,y:0},commands:[]},guest.token);lobby=await api(`rooms/${host.code}`,'GET',undefined,host.token);assert.equal(lobby.data.members.find(m=>m.id===guest.playerId).seq,1,'old input cannot overwrite new input');assert.equal((await api(`rooms/${host.code}/input`,'POST',{seq:2,move:{x:9,y:0},commands:[]},guest.token)).status,400);
const updated=JSON.parse(run('JSON.stringify(serializeMatch())'));assert.equal((await api(`rooms/${host.code}/state`,'POST',{state:updated},host.token)).status,200);const read=await api(`rooms/${host.code}`,'GET',undefined,guest.token);assert.ok(read.data.state.entities.some(e=>e.clientId===guest.playerId&&e.inventory.length===1));assert.ok(read.data.members.every(m=>m.input===undefined));assert.equal(read.data.state.ack[guest.playerId],1);
const liveMembers=(await api('rooms/'+host.code,'GET',undefined,host.token)).data.members;sandbox.disconnected=liveMembers.map(m=>m.id===guest.playerId?{...m,seen_at:Date.now()-7000}:m);run('applyRemoteInputs(disconnected);const beforeAuto={x:remote.x,y:remote.y};originals.update(.05)');assert.equal(run('remote.autoPilot'),true);assert.ok(run('distance(remote,beforeAuto)>0'),'bot moves disconnected hero');sandbox.returned=liveMembers.map(m=>({...m,seen_at:Date.now()}));run('applyRemoteInputs(returned)');assert.equal(run('remote.autoPilot'),false,'player regains control');
// New page contexts restore the persisted membership and authoritative state.
const memory=new Map(),saved={session:guest,seq:1,commandId:1,targetMode:'hero'};memory.set('rift-arena-room-v1',JSON.stringify(saved));
function newClient(){delete require.cache[require.resolve('./smoke.cjs')];const client=require('./smoke.cjs');client.sandbox.setInterval=()=>0;client.sandbox.AbortSignal=AbortSignal;client.sandbox.sessionStorage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};client.sandbox.navigator={};client.sandbox.fetch=sandbox.fetch;vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/network.js'),'utf8').replace('void restoreRoom();',''),client.sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/mobile.js'),'utf8'),client.sandbox);return client;}
const restoredGuest=newClient();await restoredGuest.run('restoreRoom()');assert.equal(restoredGuest.run('net.session.playerId'),guest.playerId);assert.equal(restoredGuest.run('game.player.inventory.length'),1);assert.equal(restoredGuest.run('net.commandId'),1);assert.ok(restoredGuest.run('net.seq>1'));restoredGuest.run('queueCommand("buy",{item:"boots"})');assert.equal(restoredGuest.run('net.pending[0].id'),2);
memory.set('rift-arena-room-v1',JSON.stringify({session:host,seq:4,commandId:0,targetMode:'nearest'}));const restoredHost=newClient();await restoredHost.run('restoreRoom()');assert.equal(restoredHost.run('net.session.host'),true);assert.equal(restoredHost.run('game.paused'),true);assert.equal(restoredHost.run('game.entities.filter(e=>e.type==="hero").length'),10);const pausedState=await api('rooms/'+host.code,'GET',undefined,guest.token);assert.equal(pausedState.data.state.paused,true);restoredHost.run('pause(false);update(.05)');assert.equal(restoredHost.run('game.paused'),false);
assert.equal((await api('rooms/'+host.code+'/input','POST',{seq:10,move:{x:0,y:0},commands:[],targetMode:'bad'},guest.token)).status,400);
// Dragged dash aims survive the guest transport even when the walking stick points elsewhere.
assert.equal((await api('rooms/'+host.code+'/input','POST',{seq:11,move:{x:0,y:1},commands:[{id:3,kind:'w',manualAim:true,aim:{x:'bad',y:100}}]},guest.token)).status,400);
restoredHost.run('const remoteDash=game.entities.find(e=>e.clientId!==net.session.playerId&&e.remoteHuman);remoteDash.x=700;remoteDash.y=500;remoteDash.cd.w=0');
assert.equal((await api('rooms/'+host.code+'/input','POST',{seq:12,move:{x:0,y:1},aim:{x:700,y:710},commands:[{id:3,kind:'w',manualAim:true,aim:{x:910,y:500}}]},guest.token)).status,200);
restoredHost.sandbox.dashMembers=(await api('rooms/'+host.code,'GET',undefined,host.token)).data.members;restoredHost.run('applyRemoteInputs(dashMembers)');assert.equal(restoredHost.run('remoteDash.x'),910);assert.equal(restoredHost.run('remoteDash.y'),500);assert.ok(restoredHost.run('remoteDash.cd.w>0'));
await api(`rooms/${host.code}/leave`,'POST',{},guest.token);assert.equal((await api(`rooms/${host.code}`,'GET',undefined,guest.token)).status,401);await api(`rooms/${host.code}/leave`,'POST',{},host.token);assert.equal((await api(`rooms/${host.code}/join`,'POST',{...config,position:'mid'})).status,409);memory.set('rift-arena-room-v1',JSON.stringify({session:guest,seq:5,commandId:2}));const revoked=newClient();await revoked.run('restoreRoom()');assert.equal(revoked.run('net.session'),null);assert.equal(memory.has('rift-arena-room-v1'),false);DB.close();console.log('PASS: online two-client room lifecycle, roster, host authority, token isolation, slot collision, input validation/order, movement, item command deduplication, shared state/ack, temporary bot takeover, guest/host reload recovery, revoked recovery, leave.');}
main().catch(e=>{console.error(e);process.exitCode=1;});
