const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const noop=()=>{},ctx=new Proxy({}, {get:(obj,key)=>obj[key]||noop,set:(obj,key,value)=>(obj[key]=value,true)});
class Element{constructor(dataset={}){this.dataset=dataset;this.style={};this.hidden=false;this.disabled=false;this.textContent='';this.innerHTML='';this.value='';this.classList={add:noop,remove:noop,toggle:noop,contains:()=>false};this.children={};this.listeners={};this.tagName='DIV';this.firstChild={textContent:''};this.lastChild={textContent:''};}setAttribute(){}querySelector(s){return this.children[s]||=new Element();}addEventListener(n,f){this.listeners[n]=f;}focus(){}showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}}
const elements={},el=id=>elements[id]||=new Element(),heroes=['sentinel','arcanist','ranger','bulwark','shade','oracle'].map(hero=>new Element({hero})),items=['blade','boots','armor','orb','fang','haste'].map(item=>new Element({item})),actions=['attack','q','w','e','recall'].map(action=>new Element({action}));
el('arena').getContext=()=>ctx;el('arena').getBoundingClientRect=()=>({width:1200,height:800,left:0,top:0});el('difficulty').value='normal';el('rune').value='power';el('joystick').firstElementChild=new Element();const registry=[];
const sandbox={console,Math,Set,Image:class{constructor(){this.complete=false;}},document:{getElementById:el,querySelector:s=>s.includes('data-action')?actions[1]:new Element(),querySelectorAll:s=>s.includes('data-hero')||s.includes('hero-card')?heroes:s.includes('data-item')?items:s.includes('data-action')?actions:[],body:new Element(),addEventListener:noop,modelContext:{registerTool:t=>registry.push(t)}},window:{addEventListener:noop,devicePixelRatio:1},ResizeObserver:class{observe(){}},requestAnimationFrame:noop,AbortController};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/hero-roster.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/lore-roster.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/game.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/navigation.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/combat.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/champions.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/lore-combat.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/utility-skills.js'),'utf8'),sandbox);const run=s=>vm.runInContext(s,sandbox),check=(s,msg)=>assert.ok(run(s),msg);
module.exports={sandbox,run,el,registry};
if(require.main===module){
run('startGame()');check('game.entities.filter(e=>e.type==="hero").length===10','5v5 roster');check('game.entities.filter(e=>e.type==="tower").length===12','two towers per lane per team');check('Math.abs(game.player.damage-65*1.15)<.001','power rune');
check('buy("blade").ok && game.player.inventory.length===1','item purchase');check('Math.abs(game.player.damage-(65*1.15+25))<.001','item changes stats');check('!buy("orb").ok','insufficient gold');const before=run('game.player.gold');check('!buy("unknown").ok','unknown item');assert.equal(run('game.player.gold'),before);
run('game.player.gold=5000');check('buy("armor").ok && game.player.maxHp===1800','armor health');run('for(let i=0;i<4;i++)buy("boots")');check('game.player.inventory.length===6 && !buy("blade").ok','inventory cap');
run('game.player.x=700;game.player.y=500;const victim=game.entities.find(e=>e.type==="hero"&&e.team===1);victim.x=750;victim.y=500;const beforeHp=victim.hp;useSkill("q")');check('victim.hp<beforeHp && game.player.cd.q>0','skill hits and starts cooldown');check('!useSkill("q")','cooldown blocks repeat');run('pause(true);const pausedTime=game.time;update(1)');check('game.time===pausedTime','pause stops simulation');run('pause(false)');
run('damage(game.player,10000,game.entities.find(e=>e.type==="monster"))');check('game.player.dead && game.kills.every(Number.isFinite)','monster kill and finite team scores');run('for(let i=0;i<200;i++)update(.05)');check('!game.player.dead && game.player.hp>0','hero respawn');
run('recall();for(let i=0;i<85;i++)update(.05)');check('distance(game.player,home(0))<1','recall returns home');
run('const enemyBase=game.entities.find(e=>e.type==="base"&&e.team===1);const baseHp=enemyBase.hp;damage(enemyBase,10000,game.player)');check('enemyBase.hp===baseHp && !game.finished','base shield');run('for(const t of game.entities.filter(e=>e.type==="tower"&&e.team===1&&e.lane===1))damage(t,10000,game.player);damage(enemyBase,10000,game.player)');check('game.finished && $("resultTitle").textContent==="ชัยชนะ"','lane breach then win');
run('lobby();$("rune").value="vitality";startGame()');check('game.player.maxHp===1680','vitality rune');run('for(const t of game.entities.filter(e=>e.type==="tower"&&e.team===0&&e.lane===0))t.dead=true;damage(game.entities.find(e=>e.type==="base"&&e.team===0),10000,game.entities.find(e=>e.type==="hero"&&e.team===1))');check('game.finished && $("resultTitle").textContent==="พ่ายแพ้"','loss result');
run('lobby();$("rune").value="speed";startGame()');check('Math.abs(game.player.speed-190*1.15)<.001','speed rune');run('for(let i=0;i<7200&&!game.finished;i++)update(.05)');check('game.entities.every(e=>Number.isFinite(e.hp)&&Number.isFinite(e.x)&&Number.isFinite(e.y))','six-minute simulation finite');check('game.kills.every(Number.isFinite)','score remains finite');assert.equal(registry.length,2);assert.throws(()=>registry[1].execute({itemId:'bad'}));console.log('PASS: roster, runes, item stats/economy/capacity, skills/cooldowns, pause, neutral kill, respawn, recall, base shield, victory/defeat, simulation, tool validation.');console.log(run('JSON.stringify({seconds:game.time,entities:game.entities.length,kills:game.kills,finished:game.finished})'));
run('lobby();chooseHero("bulwark");startGame();game.player.x=700;game.player.y=500;const enemy=game.entities.find(e=>e.type==="hero"&&e.team===1);enemy.x=740;enemy.y=500;useSkill("q");useSkill("e")');check('enemy.stun>0&&game.player.shield>0','tank stun/shield');run('lobby();chooseHero("oracle");startGame();game.player.hp=100;useSkill("q");useSkill("e")');check('game.player.hp>100&&game.player.shield>0','support healing/shield');run('lobby();chooseHero("shade");startGame();game.player.x=700;game.player.y=500;const prey=game.entities.find(e=>e.type==="hero"&&e.team===1);prey.x=950;prey.y=500;const preyHp=prey.hp;useSkill("e")');check('prey.hp<preyHp&&game.player.x>850','assassin leap');run('game.player.gold=1000;buy("armor");const healthBeforeSell=game.player.maxHp;const moneyBeforeSell=game.player.gold;sell(0)');check('game.player.maxHp===healthBeforeSell-400&&game.player.gold===moneyBeforeSell+240','sale returns gold and removes stats');console.log('PASS: tank, support, assassin, item sale.');
run('lobby();chooseHero("sentinel");startGame();const boss=game.entities.find(e=>e.camp==="boss");game.entities=game.entities.filter(e=>e.type==="hero"||e.type==="monster");game.entities.filter(e=>e.type==="hero"&&!e.player).forEach(e=>e.remoteHuman=true);game.wave=999;for(let i=0;i<1201;i++)update(.05)');check('!boss.dead','boss spawns at minute one');run('const teamGold=game.entities.filter(e=>e.type==="hero"&&e.team===0).map(e=>e.gold);damage(boss,100000,game.player)');check('boss.dead&&boss.respawn===90&&game.teamBuffs[0]===45&&game.objectiveKills[0]===1','boss reward and respawn');check('game.entities.filter(e=>e.type==="hero"&&e.team===0).every((e,i)=>e.gold===teamGold[i]+180&&e.shield>=300)','boss rewards whole team');
run('const spirit=game.entities.find(e=>e.camp==="spirit");damage(spirit,100000,game.player);game.entities=[game.player];game.player.x=500;game.player.y=500;game.player.hp=500;game.player.cd.q=6;const hpBefore=game.player.hp;update(1)');check('game.player.spirit===29&&game.player.hp>hpBefore&&game.player.cd.q===4.75','spirit buff heals and accelerates cooldown');run('for(let i=0;i<31;i++)update(1)');check('game.player.spirit===0','buff expires');
run('lobby();startGame();const p=game.player;p.x=750;p.y=500;p.range=200;const enemyHero=game.entities.find(e=>e.type==="hero"&&e.team===1);enemyHero.x=850;enemyHero.y=500;const creep=entity("minion",1,780,500);game.entities=[p,enemyHero,creep];$("targetMode").value="nearest"');check('attackTarget(game.player)===creep','nearest attack priority');run('$("targetMode").value="hero"');check('attackTarget(game.player)===enemyHero','hero priority');run('creep.hp=1;$("targetMode").value="lowest"');check('attackTarget(game.player)===creep','lowest-health priority');run('game.teamBuffs[0]=45;const tower=entity("tower",1,760,500,{hp:2000,maxHp:2000});const friendlyWave=entity("minion",0,760,550,{hp:5000,maxHp:5000});friendlyWave.remoteHuman=true;game.entities.push(tower,friendlyWave);const towerHp=tower.hp;const attackDamage=game.player.damage;game.player.attack=0;strike(game.player,tower);for(let i=0;i<4;i++)update(.05)');check('Math.abs(towerHp-tower.hp-attackDamage*1.25)<.001','team buff empowers structure attacks');run('renderScoreboard()');check('$("scoreTeams").innerHTML.includes("K/D/A")&&$("scoreTeams").innerHTML.includes("อัศวินรอยแยก")','scoreboard contains real roster');console.log('PASS: jungle buffs, boss spawn/team reward/respawn, buff expiry, attack priority, scoreboard.');
}
