const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const noop=()=>{},ctx=new Proxy({}, {get:(obj,key)=>obj[key]||noop,set:(obj,key,value)=>(obj[key]=value,true)});
class Element{constructor(dataset={}){this.dataset=dataset;this.style={};this.hidden=false;this.disabled=false;this.textContent='';this.innerHTML='';this.value='';this.classList={add:noop,remove:noop,toggle:noop};this.children={};this.listeners={};this.tagName='DIV';}setAttribute(){}querySelector(s){return this.children[s]||=new Element();}addEventListener(n,f){this.listeners[n]=f;}focus(){}showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}}
const elements={},el=id=>elements[id]||=new Element(),heroes=['sentinel','arcanist','ranger'].map(hero=>new Element({hero})),items=['blade','boots','armor','orb','fang','haste'].map(item=>new Element({item})),actions=['attack','q','w','e','recall'].map(action=>new Element({action}));
el('arena').getContext=()=>ctx;el('arena').getBoundingClientRect=()=>({width:1200,height:800,left:0,top:0});el('difficulty').value='normal';el('rune').value='power';el('joystick').firstElementChild=new Element();const registry=[];
const sandbox={console,Math,Set,document:{getElementById:el,querySelectorAll:s=>s.includes('data-hero')?heroes:s.includes('data-item')?items:s.includes('data-action')?actions:[],body:new Element(),addEventListener:noop,modelContext:{registerTool:t=>registry.push(t)}},window:{addEventListener:noop,devicePixelRatio:1},ResizeObserver:class{observe(){}},requestAnimationFrame:noop,AbortController};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/game.js'),'utf8'),sandbox);const run=s=>vm.runInContext(s,sandbox),check=(s,msg)=>assert.ok(run(s),msg);
run('startGame()');check('game.entities.filter(e=>e.type==="hero").length===10','5v5 roster');check('game.entities.filter(e=>e.type==="tower").length===12','two towers per lane per team');check('Math.abs(game.player.damage-65*1.15)<.001','power rune');
check('buy("blade").ok && game.player.inventory.length===1','item purchase');check('Math.abs(game.player.damage-(65*1.15+25))<.001','item changes stats');check('!buy("orb").ok','insufficient gold');const before=run('game.player.gold');check('!buy("unknown").ok','unknown item');assert.equal(run('game.player.gold'),before);
run('game.player.gold=5000');check('buy("armor").ok && game.player.maxHp===1800','armor health');run('for(let i=0;i<4;i++)buy("boots")');check('game.player.inventory.length===6 && !buy("blade").ok','inventory cap');
run('game.player.x=700;game.player.y=500;const victim=game.entities.find(e=>e.type==="hero"&&e.team===1);victim.x=750;victim.y=500;const beforeHp=victim.hp;useSkill("q")');check('victim.hp<beforeHp && game.player.cd.q>0','skill hits and starts cooldown');check('!useSkill("q")','cooldown blocks repeat');run('pause(true);const pausedTime=game.time;update(1)');check('game.time===pausedTime','pause stops simulation');run('pause(false)');
run('damage(game.player,10000,game.entities.find(e=>e.type==="monster"))');check('game.player.dead && game.kills.every(Number.isFinite)','monster kill and finite team scores');run('for(let i=0;i<200;i++)update(.05)');check('!game.player.dead && game.player.hp>0','hero respawn');
run('recall();for(let i=0;i<85;i++)update(.05)');check('distance(game.player,home(0))<1','recall returns home');
run('const enemyBase=game.entities.find(e=>e.type==="base"&&e.team===1);const baseHp=enemyBase.hp;damage(enemyBase,10000,game.player)');check('enemyBase.hp===baseHp && !game.finished','base shield');run('for(const t of game.entities.filter(e=>e.type==="tower"&&e.team===1&&e.lane===1))damage(t,10000,game.player);damage(enemyBase,10000,game.player)');check('game.finished && $("resultTitle").textContent==="ชัยชนะ"','lane breach then win');
run('lobby();$("rune").value="vitality";startGame()');check('game.player.maxHp===1680','vitality rune');run('for(const t of game.entities.filter(e=>e.type==="tower"&&e.team===0&&e.lane===0))t.dead=true;damage(game.entities.find(e=>e.type==="base"&&e.team===0),10000,game.entities.find(e=>e.type==="hero"&&e.team===1))');check('game.finished && $("resultTitle").textContent==="พ่ายแพ้"','loss result');
run('lobby();$("rune").value="speed";startGame()');check('Math.abs(game.player.speed-190*1.15)<.001','speed rune');run('for(let i=0;i<7200&&!game.finished;i++)update(.05)');check('game.entities.every(e=>Number.isFinite(e.hp)&&Number.isFinite(e.x)&&Number.isFinite(e.y))','six-minute simulation finite');check('game.kills.every(Number.isFinite)','score remains finite');assert.equal(registry.length,2);assert.throws(()=>registry[1].execute({itemId:'bad'}));console.log('PASS: roster, runes, item stats/economy/capacity, skills/cooldowns, pause, neutral kill, respawn, recall, base shield, victory/defeat, six-minute simulation, tool validation.');console.log(run('JSON.stringify({seconds:game.time,entities:game.entities.length,kills:game.kills,finished:game.finished})'));
