import {starterBanks} from './lesson-starters.mjs';
const positions=['off','mid','carry','jungle','roam'];
const sql=(env,s,...a)=>env.DB.prepare(s).bind(...a);
const response=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const error=(message,status=400)=>{throw Object.assign(Error(message),{status});};
const hash=async t=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t)))).map(n=>n.toString(16).padStart(2,'0')).join('');
const secret=()=>crypto.randomUUID()+crypto.randomUUID();
const text=(s,max=160)=>String(s||'').trim().slice(0,max);
async function payload(req,max=240000){const raw=await req.text();if(raw.length>max)error('ข้อมูลใหญ่เกินไป',413);try{return JSON.parse(raw);}catch{error('ข้อมูลไม่ถูกต้อง');}}
async function auth(req,env,table,extra='',args=[]){const token=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!token||token.length>100)error('กรุณาเข้าห้องใหม่',401);const found=await sql(env,`SELECT * FROM ${table} WHERE token=? ${extra}`,await hash(token),...args).first();if(!found)error('ไม่มีสิทธิ์ใช้งานห้องนี้',401);return found;}
function bank(b){if(!text(b.title)||!text(b.subject,60)||!Array.isArray(b.questions)||b.questions.length<1||b.questions.length>40)error('ชุดคำถามต้องมีชื่อ วิชา และคำถาม 1–40 ข้อ');const ids=new Set();let imageSize=0;const questions=b.questions.map(q=>{const id=text(q.id,64)||crypto.randomUUID();if(!/^[a-zA-Z0-9_-]{1,64}$/.test(id)||ids.has(id)||!text(q.prompt,500)||!Array.isArray(q.options)||q.options.length!==4||q.options.some(v=>!text(v,180))||!Number.isInteger(q.correct)||q.correct<0||q.correct>3)error('แต่ละข้อต้องมีโจทย์ ตัวเลือก 4 ข้อ และคำตอบที่ถูกต้อง');const image=String(q.image||'');if(image&&(image.length>70000||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(image)))error('รูปประกอบต้องเป็น JPG, PNG หรือ WebP ที่ย่อแล้ว');imageSize+=image.length;if(imageSize>800000)error('รูปทั้งหมดในชุดใหญ่เกินไป กรุณาลดจำนวนรูป');ids.add(id);return {id,prompt:text(q.prompt,500),options:q.options.map(v=>text(v,180)),correct:q.correct,explanation:text(q.explanation,700),...(image?{image}:{})};});return {title:text(b.title),subject:text(b.subject,60),level:text(b.level,80)||'ปรับระดับได้',questions};}
const parseBank=r=>({...r,questions:JSON.parse(r.questions)});
async function getClass(env,id){let c=await sql(env,'SELECT * FROM classrooms WHERE id=?',id).first();if(!c)error('ไม่พบห้องเรียน',404);if(c.phase==='play'&&!c.paused&&c.deadline&&Date.now()>=c.deadline){await sql(env,"UPDATE classrooms SET phase='posttest',paused=0,deadline=NULL,updated_at=? WHERE id=? AND phase='play' AND paused=0 AND deadline<=?",Date.now(),id,Date.now()).run();c=await sql(env,'SELECT * FROM classrooms WHERE id=?',id).first();}return c;}
async function owner(req,env,id){const c=await getClass(env,id),t=await auth(req,env,'teachers');if(c.teacher_id!==t.id)error('เฉพาะครูผู้สร้างห้อง',403);return c;}
function assignment(c,p){const local=c.mode==='mass'?p.slot:p.slot%10;return {arena:c.mode==='mass'?0:Math.floor(p.slot/10),roomSlot:local,team:local%2,position:positions[Math.floor(local/2)%5],capacity:c.mode==='mass'?50:10};}
function publicLesson(c,reveal=false){const lesson=JSON.parse(c.lesson);return {...lesson,questions:lesson.questions.map(q=>reveal?q:{id:q.id,prompt:q.prompt,options:q.options,...(q.image?{image:q.image}:{})})};}
function meta(c){return {code:c.id,title:c.title,mode:c.mode,mission:c.mission,phase:c.phase,paused:!!c.paused,round:c.round,focus:c.focus,minutes:c.minutes,deadline:c.deadline,capacity:50};}
async function students(env,id){return (await sql(env,'SELECT * FROM class_students WHERE class_id=? ORDER BY slot',id).all()).results;}
async function scores(env,id){return (await sql(env,'SELECT student_id,stage,round,COUNT(*) answered,SUM(correct) correct FROM lesson_answers WHERE class_id=? GROUP BY student_id,stage,round',id).all()).results;}
async function teamPlans(env,id){return (await sql(env,'SELECT arena,team,plan,author,revision,updated_at FROM class_team_plans WHERE class_id=? ORDER BY arena,team',id).all()).results;}
async function member(req,env,id){return auth(req,env,'class_students','AND class_id=?',[id]);}
async function roster(env,c,arena){const all=(await sql(env,'SELECT id,name,hero,slot,seen_at,input,seq FROM class_students WHERE class_id=? AND slot>=? AND slot<? ORDER BY slot',c.id,c.mode==='mass'?0:arena*10,c.mode==='mass'?50:(arena+1)*10).all()).results;return all.map(p=>({id:p.id,name:p.name,hero:p.hero,...assignment(c,p),rune:'power',enchant:'guard',seen_at:p.seen_at,input:p.input,seq:p.seq}));}
async function matchFor(req,env,id){const c=await getClass(env,id),p=await member(req,env,id),a=assignment(c,p);let m=await sql(env,'SELECT * FROM class_matches WHERE class_id=? AND arena=?',id,a.arena).first();const list=await roster(env,c,a.arena),now=Date.now();
  if(!m.host_id||now-m.updated_at>10000){const previous=list.find(x=>x.id===m.host_id),candidate=list.find(x=>{let active=true;try{active=JSON.parse(x.input).active!==false;}catch{}return active&&now-x.seen_at<8000;});if(candidate&&(!previous||now-previous.seen_at>8000||now-m.updated_at>12000)){await sql(env,'UPDATE class_matches SET host_id=?,updated_at=? WHERE id=? AND (host_id IS NULL OR updated_at<?)',candidate.id,now,m.id,now-10000).run();m=await sql(env,'SELECT * FROM class_matches WHERE id=?',m.id).first();}}
  return {c,p,a,m,list,host:m.host_id===p.id};
}
function matchData(v){const {c,p,a,m,list,host}=v;const state=m.state?JSON.parse(m.state):null;if(state)state.paused=!!c.paused||c.phase!=='play';return {code:c.id,status:m.status,revision:m.revision,updatedAt:m.updated_at,playerId:p.id,playerSeq:p.seq,host,capacity:a.capacity,classroom:meta(c),members:host?list:list.map(({input,seq,...v})=>v),state};}
async function recordInput(env,p,b,helpers){const input={...helpers.validateInput(b),active:b.active!==false};await sql(env,'UPDATE class_students SET input=?,seq=?,seen_at=? WHERE id=? AND seq<?',JSON.stringify(input),b.seq,Date.now(),p.id,b.seq).run();}
async function recordState(env,v,state,helpers){if(!v.host)error('เฉพาะผู้ดูแลสนาม',403);if(v.c.phase!=='play')error('ครูยังไม่เปิดช่วงเล่น',409);helpers.validateState(state);const heroes=state.entities.filter(e=>e.type==='hero');if(heroes.length!==v.a.capacity)error('จำนวนฮีโร่ไม่ตรงกับสนาม');const humanIds=heroes.filter(e=>e.clientId).map(e=>e.clientId);if(new Set(humanIds).size!==humanIds.length||humanIds.some(id=>!v.list.some(p=>p.id===id)))error('ผู้เล่นไม่ตรงกับห้องเรียน');state.paused=!!v.c.paused;const result=await sql(env,'UPDATE class_matches SET state=?,status=?,revision=revision+1,updated_at=? WHERE id=? AND host_id=?',JSON.stringify(state),state.finished?'finished':'playing',Date.now(),v.m.id,v.p.id).run();if(!result.meta.changes)error('ผู้ดูแลสนามเปลี่ยนแล้ว ลองใหม่',409);v.m={...v.m,state:JSON.stringify(state),status:state.finished?'finished':'playing',revision:v.m.revision+1,updated_at:Date.now()};}
export async function classroomApi(req,env,helpers){const url=new URL(req.url),route=url.pathname;try{
  if(!env.DB)error('ห้องเรียนยังไม่พร้อม',503);const origin=req.headers.get('origin');if(req.method!=='GET'&&origin&&origin!==url.origin)error('ต้นทางไม่ถูกต้อง',403);
  if(route==='/api/teachers'&&req.method==='POST'){const token=secret(),id=crypto.randomUUID(),now=Date.now();const initial=starterBanks();await env.DB.batch([sql(env,'INSERT INTO teachers(id,token,created_at) VALUES(?,?,?)',id,await hash(token),now),...initial.map(b=>sql(env,'INSERT INTO lesson_banks(id,teacher_id,title,subject,level,questions,updated_at) VALUES(?,?,?,?,?,?,?)',crypto.randomUUID(),id,b.title,b.subject,b.level,JSON.stringify(b.questions),now))]);return response({token,id},201);}
  if(route==='/api/lesson-banks'){const t=await auth(req,env,'teachers');if(req.method==='GET')return response({banks:(await sql(env,'SELECT * FROM lesson_banks WHERE teacher_id=? ORDER BY subject,title',t.id).all()).results.map(parseBank)});if(req.method==='POST'){const b=bank(await payload(req,1000000)),id=crypto.randomUUID();await sql(env,'INSERT INTO lesson_banks(id,teacher_id,title,subject,level,questions,updated_at) VALUES(?,?,?,?,?,?,?)',id,t.id,b.title,b.subject,b.level,JSON.stringify(b.questions),Date.now()).run();return response({id,...b},201);}}
  const bm=route.match(/^\/api\/lesson-banks\/([a-f0-9-]{36})$/);if(bm&&req.method==='PUT'){const t=await auth(req,env,'teachers'),b=bank(await payload(req,1000000));const result=await sql(env,'UPDATE lesson_banks SET title=?,subject=?,level=?,questions=?,updated_at=? WHERE id=? AND teacher_id=?',b.title,b.subject,b.level,JSON.stringify(b.questions),Date.now(),bm[1],t.id).run();if(!result.meta.changes)error('ไม่พบชุดคำถาม',404);return response({id:bm[1],...b});}
  if(route==='/api/classes'){const t=await auth(req,env,'teachers');if(req.method==='GET')return response({classes:(await sql(env,'SELECT id,title,mode,phase,updated_at FROM classrooms WHERE teacher_id=? ORDER BY updated_at DESC LIMIT 30',t.id).all()).results});if(req.method==='POST'){const b=await payload(req,4000);if(!['split','mass'].includes(b.mode)||!Number.isInteger(b.minutes)||b.minutes<2||b.minutes>30)error('เลือกรูปแบบสนาม และเวลาเล่น 2–30 นาที');const found=await sql(env,'SELECT * FROM lesson_banks WHERE id=? AND teacher_id=?',b.bankId,t.id).first();if(!found)error('เลือกชุดคำถามก่อน');const id=crypto.randomUUID().replaceAll('-','').slice(0,6).toUpperCase(),now=Date.now(),lesson=parseBank(found);await env.DB.batch([sql(env,'INSERT INTO classrooms(id,teacher_id,title,mode,lesson,mission,minutes,updated_at) VALUES(?,?,?,?,?,?,?,?)',id,t.id,text(b.title)||lesson.title,b.mode,JSON.stringify(lesson),text(b.mission,500)||'แบ่งหน้าที่ สื่อสารด้วยเหตุผล แล้วอธิบายว่าความรู้ในบทเรียนช่วยให้ทีมตัดสินใจอย่างไร',b.minutes,now),...Array.from({length:b.mode==='mass'?1:5},(_,arena)=>sql(env,'INSERT INTO class_matches(id,class_id,arena,updated_at) VALUES(?,?,?,?)',crypto.randomUUID(),id,arena,now))]);return response({code:id},201);}}
  const cm=route.match(/^\/api\/classes\/([A-Z0-9]{6})(?:\/(join|teacher|control|answer|reflection|match|frame|input|match-start|match-state|team-plan))?$/);if(!cm)error('ไม่พบเส้นทาง',404);const [,id,action]=cm;
  if(action==='join'&&req.method==='POST'){const c=await getClass(env,id);if(c.phase!=='waiting')error('ครูเริ่มกิจกรรมแล้ว ให้เข้ารอบถัดไป',409);const b=await payload(req,2000);if(!helpers.heroIds.includes(b.hero)||!text(b.name,30))error('ใส่ชื่อเล่นและเลือกฮีโร่');const token=secret(),studentId=crypto.randomUUID(),now=Date.now();const inserted=await sql(env,"WITH RECURSIVE slots(s) AS (SELECT 0 UNION ALL SELECT s+1 FROM slots WHERE s<49) INSERT INTO class_students(id,class_id,token,name,hero,slot,seen_at) SELECT ?,?,?,?,?,s,? FROM slots WHERE NOT EXISTS(SELECT 1 FROM class_students WHERE class_id=? AND slot=s) AND EXISTS(SELECT 1 FROM classrooms WHERE id=? AND phase='waiting') ORDER BY s LIMIT 1",studentId,id,await hash(token),text(b.name,30),b.hero,now,id,id).run();if(!inserted.meta.changes)error('ห้องเต็ม 50 คน หรือครูเริ่มกิจกรรมแล้ว',409);const p=await sql(env,'SELECT * FROM class_students WHERE id=?',studentId).first();return response({code:id,token,playerId:studentId,...assignment(c,p)},201);}
  if(action==='teacher'&&req.method==='GET'){const c=await owner(req,env,id),ps=await students(env,id),sc=await scores(env,id);const matches=(await sql(env,'SELECT arena,host_id,status,state,updated_at FROM class_matches WHERE class_id=? ORDER BY arena',id).all()).results.map(m=>{let s;try{s=JSON.parse(m.state);}catch{}return {arena:m.arena,hostId:m.host_id,status:m.status,updatedAt:m.updated_at,time:s?.time||0,kills:s?.kills||[0,0],finished:!!s?.finished,players:s?.entities?.filter(e=>e.type==='hero'&&e.clientId).map(e=>({id:e.clientId,kills:e.kills,deaths:e.deaths,assists:e.assists}))||[]};});const detail=(await sql(env,'SELECT student_id,stage,round,question_id,answer,correct FROM lesson_answers WHERE class_id=?',id).all()).results;return response({...meta(c),teamPlans:await teamPlans(env,id),lesson:url.searchParams.get('compact')==='1'?undefined:publicLesson(c,true),students:ps.map(({token,input,...p})=>({...p,...assignment(c,p),scores:sc.filter(s=>s.student_id===p.id)})),matches,answers:detail});}
  if(action==='control'&&req.method==='POST'){const c=await owner(req,env,id),b=await payload(req,2000),now=Date.now();if(b.action==='finish'){await sql(env,"UPDATE classrooms SET phase='finished',paused=0,deadline=NULL,focus=NULL,updated_at=? WHERE id=?",now,id).run();}
    else if(b.action==='pause'||b.action==='resume'){if(c.phase!=='play')error('พักสนามได้ในช่วงเล่น');let deadline=c.deadline;if(b.action==='pause'&&!c.paused)deadline=Math.max(0,(c.deadline||now)-now);if(b.action==='resume'&&c.paused)deadline=now+(c.deadline||0);await sql(env,'UPDATE classrooms SET paused=?,deadline=?,updated_at=? WHERE id=?',b.action==='pause'?1:0,deadline,now,id).run();}
    else if(b.action==='checkpoint'){if(c.phase!=='play')error('ถามระหว่างเกมได้ในช่วงเล่น');if(!JSON.parse(c.lesson).questions.some(q=>q.id===b.questionId))error('ไม่พบคำถาม');await sql(env,"UPDATE classrooms SET phase='checkpoint',paused=1,round=round+1,focus=?,deadline=?,updated_at=? WHERE id=?",b.questionId,c.paused?c.deadline:Math.max(0,(c.deadline||now)-now),now,id).run();}
    else{const next={waiting:'pretest',pretest:'briefing',briefing:'play',checkpoint:'play',play:'posttest',posttest:'reflection',reflection:'finished'}[c.phase];if(!next||b.action!=='next')error('ไม่สามารถเปลี่ยนช่วงกิจกรรมได้',409);const count=await sql(env,'SELECT COUNT(*) n FROM class_students WHERE class_id=?',id).first();if(!count.n)error('รอนักเรียนเข้าห้องอย่างน้อย 1 คน');const deadline=next==='play'?now+(c.phase==='checkpoint'?(c.deadline||0):c.minutes*60000):null;await sql(env,'UPDATE classrooms SET phase=?,paused=0,deadline=?,focus=NULL,updated_at=? WHERE id=?',next,deadline,now,id).run();}return response({ok:true,...meta(await getClass(env,id))});}
  if(!action&&req.method==='GET'){const c=await getClass(env,id),p=await member(req,env,id);await sql(env,'UPDATE class_students SET seen_at=? WHERE id=?',Date.now(),p.id).run();const ans=(await sql(env,'SELECT stage,round,question_id,answer,correct FROM lesson_answers WHERE student_id=?',p.id).all()).results;const count=await sql(env,'SELECT COUNT(*) n FROM class_students WHERE class_id=?',id).first();return response({...meta(c),student:{id:p.id,name:p.name,hero:p.hero,reflection:p.reflection,...assignment(c,p)},memberCount:count.n,teamPlan:(await teamPlans(env,id)).find(t=>t.arena===assignment(c,p).arena&&t.team===assignment(c,p).team)||null,lesson:url.searchParams.get('compact')==='1'?undefined:publicLesson(c,['briefing','reflection','finished'].includes(c.phase)),answers:ans.map(a=>['posttest','checkpoint'].includes(a.stage)?{...a,feedback:JSON.parse(c.lesson).questions.filter(q=>q.id===a.question_id).map(q=>({correct:q.correct,explanation:q.explanation}))[0]}:a)});}
  if(action==='answer'&&req.method==='POST'){const c=await getClass(env,id),p=await member(req,env,id),b=await payload(req,2000);if(!['pretest','posttest','checkpoint'].includes(c.phase)||b.stage!==c.phase||b.round!==c.round)error('ช่วงคำถามนี้ปิดแล้ว',409);const q=JSON.parse(c.lesson).questions.find(q=>q.id===b.questionId);if(!q||c.phase==='checkpoint'&&q.id!==c.focus||!Number.isInteger(b.answer)||b.answer<0||b.answer>3)error('คำตอบไม่ถูกต้อง');await sql(env,'INSERT INTO lesson_answers(id,class_id,student_id,stage,round,question_id,answer,correct,answered_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(student_id,stage,round,question_id) DO NOTHING',crypto.randomUUID(),id,p.id,c.phase,c.round,q.id,b.answer,Number(b.answer===q.correct),Date.now()).run();const saved=await sql(env,'SELECT answer FROM lesson_answers WHERE student_id=? AND stage=? AND round=? AND question_id=?',p.id,c.phase,c.round,q.id).first();return response({ok:true,answer:saved.answer});}
  if(action==='team-plan'&&req.method==='POST'){const c=await getClass(env,id),p=await member(req,env,id),a=assignment(c,p);if(!['waiting','briefing','play'].includes(c.phase))error('แก้แผนได้ช่วงรอ เรียนรู้ หรือภารกิจ',409);const b=await payload(req,4000),plan=text(b.plan,600);if(!plan||!Number.isInteger(b.revision)||b.revision<0)error('เขียนแผนและบทบาทของทีมก่อน');const changed=await sql(env,'INSERT INTO class_team_plans(id,class_id,arena,team,plan,author,revision,updated_at) SELECT ?,?,?,?,?,?,1,? WHERE ?=0 OR EXISTS(SELECT 1 FROM class_team_plans WHERE class_id=? AND arena=? AND team=?) ON CONFLICT(class_id,arena,team) DO UPDATE SET plan=excluded.plan,author=excluded.author,revision=class_team_plans.revision+1,updated_at=excluded.updated_at WHERE class_team_plans.revision=?',crypto.randomUUID(),id,a.arena,a.team,plan,p.name,Date.now(),b.revision,id,a.arena,a.team,b.revision).run();if(!changed.meta.changes)error('เพื่อนแก้แผนแล้ว โหลดแผนล่าสุดก่อนบันทึก',409);return response({ok:true});}
  if(action==='reflection'&&req.method==='POST'){const c=await getClass(env,id),p=await member(req,env,id);if(c.phase!=='reflection')error('ครูยังไม่เปิดช่วงสะท้อนคิด',409);const b=await payload(req,5000);const value={knowledge:text(b.knowledge,600),teamwork:text(b.teamwork,600)};if(!value.knowledge||!value.teamwork)error('เขียนสะท้อนคิดทั้งสองข้อ');await sql(env,'UPDATE class_students SET reflection=?,seen_at=? WHERE id=?',JSON.stringify(value),Date.now(),p.id).run();return response({ok:true});}
  if(action==='input'&&req.method==='POST'){const p=await member(req,env,id);await recordInput(env,p,await payload(req,16000),helpers);return response({ok:true});}
  if(['match','frame','match-start','match-state'].includes(action)){const v=await matchFor(req,env,id);await sql(env,'UPDATE class_students SET seen_at=? WHERE id=?',Date.now(),v.p.id).run();if(action==='match'&&req.method==='GET')return response(matchData(v));if(req.method==='POST'){
    const b=await payload(req,512000);if(action==='frame'){await recordInput(env,v.p,b.input,helpers);if(b.state&&v.host&&v.c.phase==='play')await recordState(env,v,b.state,helpers);const local=v.list.find(p=>p.id===v.p.id);if(local&&b.input.seq>local.seq){local.input=JSON.stringify({...helpers.validateInput(b.input),active:b.input.active!==false});local.seq=b.input.seq;local.seen_at=Date.now();}const data=matchData(v);if(v.host&&b.state)data.state=null;return response(data);}
    if(['match-start','match-state'].includes(action)){await recordState(env,v,b.state,helpers);return response({ok:true});}
  }}error('ไม่รองรับคำสั่งนี้',405);
}catch(e){if(e.status)return response({error:e.message},e.status);if(String(e.message).includes('UNIQUE constraint'))return response({error:'ห้องกำลังรับผู้เล่นพร้อมกัน กรุณาลองอีกครั้ง'},409);console.error('Classroom service failure',e.message);return response({error:'บันทึกห้องเรียนไม่สำเร็จ ลองใหม่ได้โดยข้อมูลที่กรอกยังอยู่'},503);}}
