import {makeSnow,stepSnow} from './snow-game.mjs';
const sql=(env,s,...args)=>env.DB.prepare(s).bind(...args);
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status});};
export async function progress(env,studentId){const existing=await sql(env,'SELECT * FROM class_play_progress WHERE student_id=?',studentId).first();if(existing)return existing;await sql(env,'INSERT INTO class_play_progress(student_id) VALUES(?) ON CONFLICT DO NOTHING',studentId).run();return sql(env,'SELECT * FROM class_play_progress WHERE student_id=?',studentId).first();}
export function resources(p){return {energy:Math.max(0,Math.min(3000,Math.floor(p.credits-p.spent))),ammo:Math.max(0,p.ammo-p.shots),cursor:p.cursor,correct:p.correct,attempts:p.cursor};}
export async function question(env,c,p){const r=await progress(env,p.id),questions=JSON.parse(c.lesson).questions,q=questions[(r.cursor+p.slot)%questions.length];return {cursor:r.cursor,resources:resources(r),question:{id:q.id,prompt:q.prompt,options:q.options,...(q.image?{image:q.image}:{})}};}
export async function answer(env,c,p,b){if(c.phase!=='play')fail('ช่วงเล่นปิดแล้ว',409);if(c.paused)fail('ครูพักสนามอยู่ เก็บคำตอบไว้แล้วจะส่งเมื่อเล่นต่อ',423);if(!Number.isSafeInteger(b.cursor)||b.cursor<0||b.cursor>10000||!Number.isInteger(b.answer)||b.answer<0||b.answer>3)fail('คำตอบไม่ถูกต้อง');const r=await progress(env,p.id),questions=JSON.parse(c.lesson).questions,q=questions[(b.cursor+p.slot)%questions.length],now=Date.now();if(b.questionId!==q.id)fail('คำถามเปลี่ยนแล้ว เปิดคำถามล่าสุด',409);let saved=await sql(env,"SELECT answer,correct FROM lesson_answers WHERE student_id=? AND stage='practice' AND round=? AND question_id=?",p.id,b.cursor,q.id).first();if(!saved){if(r.cursor!==b.cursor)fail('คำถามเปลี่ยนแล้ว เปิดคำถามล่าสุด',409);if(now-r.answered_at<800)fail('อ่านโจทย์และรอสักครู่ก่อนส่งคำตอบถัดไป',429);const correct=Number(b.answer===q.correct);await env.DB.batch([
    sql(env,"INSERT INTO lesson_answers(id,class_id,student_id,stage,round,question_id,answer,correct,answered_at) SELECT ?,?,?,'practice',?,?,?,?,? WHERE EXISTS(SELECT 1 FROM class_play_progress WHERE student_id=? AND cursor=?) AND EXISTS(SELECT 1 FROM classrooms WHERE id=? AND phase='play' AND paused=0) ON CONFLICT(student_id,stage,round,question_id) DO NOTHING",crypto.randomUUID(),c.id,p.id,b.cursor,q.id,b.answer,correct,now,p.id,b.cursor,c.id),
    sql(env,"UPDATE class_play_progress SET cursor=cursor+1,correct=correct+?,credits=MIN(spent+3000,credits+?),ammo=MIN(shots+36,ammo+?),answered_at=? WHERE student_id=? AND cursor=? AND EXISTS(SELECT 1 FROM lesson_answers WHERE student_id=? AND stage='practice' AND round=? AND question_id=?)",correct,correct?1000:0,correct?6:0,now,p.id,b.cursor,p.id,b.cursor,q.id)
  ]);saved=await sql(env,"SELECT answer,correct FROM lesson_answers WHERE student_id=? AND stage='practice' AND round=? AND question_id=?",p.id,b.cursor,q.id).first();if(!saved)fail('ช่วงคำถามนี้ปิดแล้ว',409);}
  return {answer:saved.answer,correct:!!saved.correct,feedback:{correct:q.correct,explanation:q.explanation},resources:resources(await progress(env,p.id)),cursor:b.cursor};}
export async function spendMovement(env,c,p,b){if(c.phase!=='play'||c.paused||c.activity==='snow'||!c.energy_questions)return;const now=Date.now(),r=await progress(env,p.id);let previous={};try{previous=JSON.parse(p.input);}catch{}const dt=Math.min(.6,Math.max(0,(now-r.moved_at)/1000)),moving=previous.active!==false&&!previous.studying&&(previous.moving||Math.hypot(previous.move?.x||0,previous.move?.y||0)>.1);await sql(env,'UPDATE class_play_progress SET spent=MIN(credits,spent+?),moved_at=? WHERE student_id=? AND moved_at=?',moving?dt*40:0,now,p.id,r.moved_at).run();}
export async function attachResources(env,list){if(!list.length)return [];const rows=(await sql(env,`SELECT * FROM class_play_progress WHERE student_id IN (${list.map(()=>'?').join(',')})`,...list.map(p=>p.id)).all()).results;const byId=new Map(rows.map(r=>[r.student_id,r]));return list.map(p=>({...p,resources:resources(byId.get(p.id)||{credits:1000,spent:0,ammo:3,shots:0,cursor:0,correct:0})}));}
export async function snowFrame(env,c,p,input){if(c.activity!=='snow')fail('ห้องนี้ใช้สนาม MOBA',409);if(c.phase!=='play')fail('ครูยังไม่เปิดช่วงเล่น',409);let row=await sql(env,'SELECT * FROM class_snow_states WHERE class_id=? AND arena=?',c.id,p.arena).first();const list=(await sql(env,'SELECT s.id,s.name,s.hero,s.slot,s.seen_at,s.input,r.credits,r.ammo,r.spent,r.shots FROM class_students s JOIN class_play_progress r ON r.student_id=s.id WHERE s.class_id=? AND s.slot>=? AND s.slot<? ORDER BY s.slot',c.id,c.mode==='mass'?0:p.arena*10,c.mode==='mass'?50:(p.arena+1)*10).all()).results;
  if(!row){const s=makeSnow(list,Date.now());await sql(env,'INSERT INTO class_snow_states(class_id,arena,state,updated_at) VALUES(?,?,?,?) ON CONFLICT DO NOTHING',c.id,p.arena,JSON.stringify(s),Date.now()).run();row=await sql(env,'SELECT * FROM class_snow_states WHERE class_id=? AND arena=?',c.id,p.arena).first();}
  const now=Date.now();if(now-row.updated_at>=120){const state=stepSnow(JSON.parse(row.state),list,now,!!c.paused);state.tick=crypto.randomUUID();const encoded=JSON.stringify(state);await env.DB.batch([sql(env,'UPDATE class_snow_states SET state=?,updated_at=?,revision=revision+1 WHERE class_id=? AND arena=? AND revision=?',encoded,now,c.id,p.arena,row.revision),sql(env,"UPDATE class_play_progress SET spent=MAX(spent,COALESCE((SELECT json_extract(value,'$.spent') FROM json_each(?,'$.players') WHERE json_extract(value,'$.id')=student_id),spent)),shots=MAX(shots,COALESCE((SELECT json_extract(value,'$.shots') FROM json_each(?,'$.players') WHERE json_extract(value,'$.id')=student_id),shots)) WHERE student_id IN (SELECT id FROM class_students WHERE class_id=? AND slot>=? AND slot<?) AND EXISTS(SELECT 1 FROM class_snow_states WHERE class_id=? AND arena=? AND revision=? AND json_extract(state,'$.tick')=?)",encoded,encoded,c.id,c.mode==='mass'?0:p.arena*10,c.mode==='mass'?50:(p.arena+1)*10,c.id,p.arena,row.revision+1,state.tick)]);row=await sql(env,'SELECT * FROM class_snow_states WHERE class_id=? AND arena=?',c.id,p.arena).first();}
  const state=JSON.parse(row.state);state.paused=!!c.paused;return {state,resources:resources(await progress(env,p.id)),revision:row.revision};}
