// Small deterministic simulation. The classroom service advances and stores it;
// clients send controls, never positions, roles, hits, energy, or scores.
export const SNOW_WORLD={width:1800,height:1200,obstacles:[{x:340,y:260,w:220,h:80},{x:790,y:220,w:100,h:250},{x:1180,y:300,w:240,h:80},{x:400,y:680,w:100,h:250},{x:830,y:710,w:200,h:90},{x:1270,y:790,w:100,h:230}]};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const blocked=(x,y,r=18)=>SNOW_WORLD.obstacles.some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h);
export function makeSnow(players,now){const initial=players.length>1?players.at(-1).id:'snow-bot';const list=players.map((p,i)=>({id:p.id,name:p.name,hero:p.hero,x:120+(i%8)*160,y:130+Math.floor(i/8)*125,zombie:p.id===initial,hp:3,spent:p.spent||0,shots:0,lastShot:0,stun:0,immune:5,survived:0}));for(const p of list){while(blocked(p.x,p.y)){p.y+=60;if(p.y>1150){p.y=80;p.x+=60;}}}if(players.length===1)list.push({id:initial,name:'ซอมบี้ฝึกหัด (บอต)',hero:'bulwark',x:1650,y:1050,zombie:true,hp:3,spent:0,shots:0,lastShot:0,stun:0,immune:0,survived:0,bot:true});return {kind:'snow',time:0,updatedAt:now,finished:false,players:list,balls:[],nextBall:1,world:SNOW_WORLD};}
export function stepSnow(state,members,now,paused=false){const s=structuredClone(state),dt=clamp((now-s.updatedAt)/1000,0,.4);s.updatedAt=now;if(paused||s.finished)return s;s.time+=dt;const lookup=new Map(members.map(p=>[p.id,p]));for(const p of s.players){const m=lookup.get(p.id);let input={};if(m&&now-m.seen_at<2000){try{input=JSON.parse(m.input);}catch{}}if(p.bot&&s.time>8){const t=s.players.filter(t=>!t.zombie).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(t){const d=Math.hypot(t.x-p.x,t.y-p.y)||1;input={move:{x:(t.x-p.x)/d,y:(t.y-p.y)/d},aim:{x:t.x,y:t.y},attack:true};}}
    p.immune=Math.max(0,p.immune-dt);p.stun=Math.max(0,p.stun-dt);if(!p.zombie&&m&&input.active!==false&&now-m.seen_at<2000)p.survived+=dt;const energy=Math.max(0,(m?.credits||0)-p.spent),moving=input.active!==false&&!input.studying&&p.stun<=0&&(p.zombie||energy>0);let dx=moving?Number(input.move?.x)||0:0,dy=moving?Number(input.move?.y)||0:0;const len=Math.hypot(dx,dy);if(len>1){dx/=len;dy/=len;}const speed=p.zombie?(p.bot?110:190):225,tx=clamp(p.x+dx*speed*dt,28,SNOW_WORLD.width-28),ty=clamp(p.y+dy*speed*dt,28,SNOW_WORLD.height-28);const oldX=p.x,oldY=p.y;if(!blocked(tx,p.y))p.x=tx;if(!blocked(p.x,ty))p.y=ty;if(!p.zombie)p.spent+=Math.min(energy,Math.hypot(p.x-oldX,p.y-oldY)/speed*40);
    const ammo=p.bot?999:Math.max(0,(m?.ammo||0)-p.shots),fire=input.active!==false&&!input.studying&&input.attack&&ammo>0&&p.stun<=0&&s.time-p.lastShot>=(p.bot?2.8:.65);if(fire){const ax=Number(input.aim?.x)||p.x+1,ay=Number(input.aim?.y)||p.y,d=Math.hypot(ax-p.x,ay-p.y)||1;s.balls.push({id:s.nextBall++,owner:p.id,zombie:p.zombie,x:p.x,y:p.y,dx:(ax-p.x)/d,dy:(ay-p.y)/d,life:1.25});p.shots++;p.lastShot=s.time;}}
  s.balls=s.balls.filter(b=>{b.life-=dt;const ox=b.x,oy=b.y;b.x+=b.dx*640*dt;b.y+=b.dy*640*dt;if(b.life<=0||blocked(b.x,b.y,6)||b.x<0||b.y<0||b.x>SNOW_WORLD.width||b.y>SNOW_WORLD.height)return false;const vx=b.x-ox,vy=b.y-oy,vv=vx*vx+vy*vy;for(const p of s.players){if(p.zombie===b.zombie||p.immune>0)continue;const t=vv?clamp(((p.x-ox)*vx+(p.y-oy)*vy)/vv,0,1):0;if(Math.hypot(p.x-ox-vx*t,p.y-oy-vy*t)>24)continue;if(p.zombie)p.stun=1.5;else{p.hp--;p.immune=1;if(p.hp<=0){p.zombie=true;p.hp=3;p.immune=3;}}return false;}return true;});if(s.players.every(p=>p.zombie))s.finished=true;return s;}
