// Small deterministic simulation. The classroom service advances and stores it;
// clients send controls, never positions, roles, hits, energy, or scores.
export const SNOW_WORLD={width:1800,height:1200,obstacles:[{x:340,y:260,w:220,h:80},{x:790,y:220,w:100,h:250},{x:1180,y:300,w:240,h:80},{x:400,y:680,w:100,h:250},{x:830,y:710,w:200,h:90},{x:1270,y:790,w:100,h:230}]};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const blocked=(x,y,r=18)=>SNOW_WORLD.obstacles.some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h);
export function makeSnow(players,now,capacity=Math.max(2,players.length)){
  capacity=clamp(capacity,2,50);const heroes=['sentinel','arcanist','ranger','bulwark','shade','oracle'],bySlot=new Map(players.map((p,i)=>[(p.slot??i)%capacity,p]));
  const list=Array.from({length:capacity},(_,slot)=>{const p=bySlot.get(slot),bot=!p;return {id:p?.id||'snow-bot-'+slot,name:p?.name||'บอตหิมะ '+(slot+1),hero:p?.hero||heroes[slot%heroes.length],roomSlot:slot,x:120+(slot%8)*160,y:130+Math.floor(slot/8)*125,zombie:false,hp:3,spent:p?.spent||0,shots:p?.shots||0,lastShot:0,stun:0,immune:5,survived:0,...(bot?{bot:true,credits:1000,ammo:3,nextRefill:8}: {})};});
  const initial=list.filter(p=>p.bot).at(-1)||list.at(-1);initial.zombie=true;if(initial.bot){initial.x=1650;initial.y=1050;}
  for(const p of list){while(blocked(p.x,p.y)){p.y+=60;if(p.y>1150){p.y=80;p.x+=60;}}}
  return {kind:'snow',time:0,updatedAt:now,finished:false,players:list,balls:[],nextBall:1,world:SNOW_WORLD};
}
function botDirection(p,target,speed){const angle=Math.atan2(target.y-p.y,target.x-p.x);let best={x:0,y:0},score=Infinity;for(const turn of [0,.5,-.5,1,-1,1.6,-1.6,Math.PI]){const dx=Math.cos(angle+turn),dy=Math.sin(angle+turn),x=clamp(p.x+dx*speed*.8,28,SNOW_WORLD.width-28),y=clamp(p.y+dy*speed*.8,28,SNOW_WORLD.height-28);if(blocked(x,y)||blocked((x+p.x)/2,(y+p.y)/2))continue;const value=Math.hypot(target.x-x,target.y-y)+Math.abs(turn)*12;if(value<score){score=value;best={x:dx,y:dy};}}return best;}
export function stepSnow(state,members,now,paused=false){const s=structuredClone(state),dt=clamp((now-s.updatedAt)/1000,0,.4);s.updatedAt=now;if(paused||s.finished)return s;s.time+=dt;const lookup=new Map(members.map(p=>[p.id,p]));for(const p of s.players){let m=lookup.get(p.id);let input={};if(m&&now-m.seen_at<2000){try{input=JSON.parse(m.input);}catch{}}if(p.bot){p.credits??=1000;p.ammo??=3;p.nextRefill??=8;if(s.time>=p.nextRefill){p.credits=p.spent+Math.min(3000,Math.max(0,p.credits-p.spent)+1000);p.ammo=p.shots+Math.min(36,Math.max(0,p.ammo-p.shots)+6);p.nextRefill=s.time+8;}m={credits:p.credits,ammo:p.ammo,seen_at:now};if(s.time>8){const t=s.players.filter(t=>t.zombie!==p.zombie).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(t){const distance=Math.hypot(t.x-p.x,t.y-p.y)||1,slot=p.roomSlot||0,wander={x:150+((slot*241+Math.floor(s.time/12)*193)%1450),y:100+((slot*137+Math.floor(s.time/12)*97)%950)},target=p.zombie?t:distance<430?{x:clamp(p.x+(p.x-t.x)/distance*450,40,1760),y:clamp(p.y+(p.y-t.y)/distance*450,40,1160)}:wander;input={move:botDirection(p,target,p.zombie?145:185),aim:{x:t.x,y:t.y},attack:distance<650};}}}
    p.immune=Math.max(0,p.immune-dt);p.stun=Math.max(0,p.stun-dt);if(!p.zombie&&m&&input.active!==false&&now-m.seen_at<2000)p.survived+=dt;const energy=Math.max(0,(m?.credits||0)-p.spent),moving=input.active!==false&&!input.studying&&p.stun<=0&&(p.zombie||energy>0);let dx=moving?Number(input.move?.x)||0:0,dy=moving?Number(input.move?.y)||0:0;const len=Math.hypot(dx,dy);if(len>1){dx/=len;dy/=len;}const speed=p.bot?(p.zombie?145:185):p.zombie?190:225,tx=clamp(p.x+dx*speed*dt,28,SNOW_WORLD.width-28),ty=clamp(p.y+dy*speed*dt,28,SNOW_WORLD.height-28);const oldX=p.x,oldY=p.y;if(!blocked(tx,p.y))p.x=tx;if(!blocked(p.x,ty))p.y=ty;if(!p.zombie)p.spent+=Math.min(energy,Math.hypot(p.x-oldX,p.y-oldY)/speed*40);
    const ammo=Math.max(0,(m?.ammo||0)-p.shots),fire=input.active!==false&&!input.studying&&input.attack&&ammo>0&&p.stun<=0&&s.time-p.lastShot>=(p.bot?2.8:.65);if(fire){const ax=Number(input.aim?.x)||p.x+1,ay=Number(input.aim?.y)||p.y,d=Math.hypot(ax-p.x,ay-p.y)||1;s.balls.push({id:s.nextBall++,owner:p.id,zombie:p.zombie,x:p.x,y:p.y,dx:(ax-p.x)/d,dy:(ay-p.y)/d,life:1.25});p.shots++;p.lastShot=s.time;}}
  s.balls=s.balls.filter(b=>{b.life-=dt;const ox=b.x,oy=b.y;b.x+=b.dx*640*dt;b.y+=b.dy*640*dt;if(b.life<=0||blocked(b.x,b.y,6)||b.x<0||b.y<0||b.x>SNOW_WORLD.width||b.y>SNOW_WORLD.height)return false;const vx=b.x-ox,vy=b.y-oy,vv=vx*vx+vy*vy;for(const p of s.players){if(p.zombie===b.zombie||p.immune>0)continue;const t=vv?clamp(((p.x-ox)*vx+(p.y-oy)*vy)/vv,0,1):0;if(Math.hypot(p.x-ox-vx*t,p.y-oy-vy*t)>24)continue;if(p.zombie)p.stun=1.5;else{p.hp--;p.immune=1;if(p.hp<=0){p.zombie=true;p.hp=3;p.immune=3;}}return false;}return true;});if(s.players.every(p=>p.zombie))s.finished=true;return s;}
