import {classroomApi} from './classroom.mjs';
const HERO_IDS=['sentinel','arcanist','ranger','bulwark','shade','oracle','stuart','capheny','maloch','ignis','mortos','taara','elsu','hayate','flowborn','zata'];
const POSITIONS=['off','mid','carry','jungle','roam'];
const RUNES=['power','vitality','speed'],ENCHANTS=['fury','guard','recovery'];
const ITEMS=['blade','boots','armor','orb','fang','haste'];
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const query=(env,sql,...args)=>env.DB.prepare(sql).bind(...args);
const digest=async token=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))).map(n=>n.toString(16).padStart(2,'0')).join('');
const choice=(value,list,label)=>{if(!list.includes(value))fail('ค่า'+label+'ไม่ถูกต้อง');return value;};
function config(b){return {name:String(b.name||'นักรบ').trim().slice(0,20)||'นักรบ',team:choice(b.team,[0,1],'ทีม'),position:choice(b.position,POSITIONS,'ตำแหน่ง'),hero:choice(b.hero,HERO_IDS,'ฮีโร่'),rune:choice(b.rune,RUNES,'รูน'),enchant:choice(b.enchant,ENCHANTS,'พลังแฝง')};}
async function body(request,max=140000){const declared=Number(request.headers.get('content-length'));if(declared>max)fail('ข้อมูลใหญ่เกินไป',413);const raw=await request.text();if(raw.length>max)fail('ข้อมูลใหญ่เกินไป',413);try{return JSON.parse(raw);}catch{fail('ข้อมูลไม่ถูกต้อง');}}
function point(v){return v&&Number.isFinite(v.x)&&Number.isFinite(v.y)&&Math.abs(v.x)<3000&&Math.abs(v.y)<3000?{x:v.x,y:v.y}:null;}
function validateInput(b){if(!Number.isSafeInteger(b.seq)||b.seq<0)fail('ลำดับคำสั่งไม่ถูกต้อง');const move=point(b.move)||{x:0,y:0};if(Math.abs(move.x)>1||Math.abs(move.y)>1)fail('ทิศเดินไม่ถูกต้อง');const cmds=Array.isArray(b.commands)?b.commands:[];if(cmds.length>24)fail('คำสั่งมากเกินไป');for(const c of cmds){if(!Number.isSafeInteger(c.id)||c.id<0||!['q','w','e','recall','attack','buy','sell','walk'].includes(c.kind))fail('คำสั่งไม่ถูกต้อง');if(c.kind==='buy'&&!ITEMS.includes(c.item))fail('ไอเทมไม่ถูกต้อง');if(c.kind==='sell'&&(!Number.isInteger(c.slot)||c.slot<0||c.slot>5))fail('ช่องไอเทมไม่ถูกต้อง');if(['q','w','e'].includes(c.kind)&&c.aim!==undefined&&!point(c.aim))fail('ทิศสกิลไม่ถูกต้อง');if(c.kind==='walk'&&!point(c.point))fail('จุดเดินไม่ถูกต้อง');}return {targetMode:b.targetMode===undefined?'nearest':choice(b.targetMode,['nearest','hero','lowest','tower'],'เป้าโจมตี'),move,aim:point(b.aim)||{x:750,y:500},attack:b.attack===true,commands:cmds};}
function validateState(state){if(!state||typeof state!=='object'||!Array.isArray(state.entities)||state.entities.length>350||!Number.isFinite(state.time)||state.time<0||!Array.isArray(state.kills)||state.kills.length!==2||!state.kills.every(Number.isFinite))fail('สถานะแมตช์ไม่ถูกต้อง');const ids=new Set();for(const e of state.entities){if(!Number.isSafeInteger(e.id)||ids.has(e.id)||!['hero','tower','minion','base','monster'].includes(e.type)||![0,1,2].includes(e.team)||![e.x,e.y,e.hp,e.maxHp].every(Number.isFinite))fail('ข้อมูลตัวละครไม่ถูกต้อง');ids.add(e.id);}return state;}
async function member(request,env,id){const token=request.headers.get('authorization')?.replace(/^Bearer /,'');if(!token||token.length>100)fail('ไม่มีสิทธิ์เข้าห้อง',401);const hashed=await digest(token);const player=await query(env,'SELECT * FROM players WHERE room_id = ? AND token = ?',id,hashed).first();if(!player)fail('ไม่มีสิทธิ์เข้าห้อง',401);return {player,hashed};}
async function findRoom(env,id){const room=await query(env,'SELECT * FROM rooms WHERE id = ?',id).first();if(!room||Date.now()-room.updated_at>3600000)fail('ไม่พบห้อง หรือห้องหมดอายุแล้ว',404);return room;}
async function requireHost(request,env,id){const room=await findRoom(env,id),auth=await member(request,env,id);if(room.host_token!==auth.hashed)fail('เฉพาะเจ้าของห้องเท่านั้น',403);return {...auth,room};}
async function api(request,env){if(!env.DB)return json({error:'ห้องออนไลน์ยังไม่พร้อม ลองใหม่อีกครั้ง'},503);const url=new URL(request.url),origin=request.headers.get('origin');if(request.method!=='GET'&&origin&&origin!==url.origin)return json({error:'ต้นทางไม่ถูกต้อง'},403);
try{if(url.pathname==='/api/health')return json({ok:true});
if(url.pathname==='/api/rooms'&&request.method==='POST'){const c=config(await body(request,4000)),token=crypto.randomUUID()+crypto.randomUUID(),hashed=await digest(token),playerId=crypto.randomUUID(),id=crypto.randomUUID().replaceAll('-','').slice(0,6).toUpperCase(),now=Date.now();await env.DB.batch([query(env,'DELETE FROM players WHERE room_id IN (SELECT id FROM rooms WHERE updated_at < ? LIMIT 100)',now-3600000),query(env,'DELETE FROM rooms WHERE id IN (SELECT id FROM rooms WHERE updated_at < ? LIMIT 100)',now-3600000),query(env,'INSERT INTO rooms (id,host_token,updated_at) VALUES (?,?,?)',id,hashed,now),query(env,'INSERT INTO players (id,room_id,token,name,team,position,hero,rune,enchant,seen_at) VALUES (?,?,?,?,?,?,?,?,?,?)',playerId,id,hashed,c.name,c.team,c.position,c.hero,c.rune,c.enchant,now)]);return json({code:id,token,playerId,host:true},201);}
const match=url.pathname.match(/^\/api\/rooms\/([A-Z0-9]{6})(?:\/(join|config|start|state|input|leave))?$/);if(!match)fail('ไม่พบเส้นทาง',404);const [,id,action]=match;
if(action==='join'&&request.method==='POST'){const room=await findRoom(env,id);if(room.status!=='waiting')fail('แมตช์เริ่มไปแล้ว สร้างห้องใหม่เพื่อเล่นรอบถัดไป',409);const c=config(await body(request,4000)),token=crypto.randomUUID()+crypto.randomUUID(),playerId=crypto.randomUUID();const inserted=await query(env,"INSERT INTO players (id,room_id,token,name,team,position,hero,rune,enchant,seen_at) SELECT ?,?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM rooms WHERE id=? AND status='waiting')",playerId,id,await digest(token),c.name,c.team,c.position,c.hero,c.rune,c.enchant,Date.now(),id).run();if(!inserted.meta.changes)fail('แมตช์เริ่มไปแล้ว',409);return json({code:id,token,playerId,host:false},201);}
if(!action&&request.method==='GET'){const room=await findRoom(env,id),{player,hashed}=await member(request,env,id),host=hashed===room.host_token;const columns=host?'id,name,team,position,hero,rune,enchant,seen_at,input,seq':'id,name,team,position,hero,rune,enchant,seen_at';const list=(await query(env,`SELECT ${columns} FROM players WHERE room_id = ? ORDER BY team,position`,id).all()).results;return json({code:id,status:room.status,revision:room.revision,updatedAt:room.updated_at,playerId:player.id,playerSeq:player.seq,playerInput:player.input,host,members:list,state:room.state?JSON.parse(room.state):null});}
if(action==='config'&&request.method==='POST'){const room=await findRoom(env,id),{player}=await member(request,env,id);if(room.status!=='waiting')fail('เปลี่ยนตัวเลือกได้ก่อนเริ่มแมตช์เท่านั้น',409);const c=config(await body(request,4000));await query(env,'UPDATE players SET name=?,team=?,position=?,hero=?,rune=?,enchant=?,seen_at=? WHERE id=?',c.name,c.team,c.position,c.hero,c.rune,c.enchant,Date.now(),player.id).run();return json({ok:true});}
if((action==='start'||action==='state')&&request.method==='POST'){const {room,player}=await requireHost(request,env,id),b=await body(request),state=validateState(b.state);if(action==='start'&&room.status!=='waiting')fail('แมตช์เริ่มแล้ว',409);if(action==='state'&&!['playing','finished'].includes(room.status))fail('แมตช์ยังไม่เริ่ม หรือห้องปิดแล้ว',409);await env.DB.batch([query(env,"UPDATE rooms SET state=?,status=?,revision=revision+1,updated_at=? WHERE id=?",JSON.stringify(state),state.finished?'finished':'playing',Date.now(),id),query(env,'UPDATE players SET seen_at=? WHERE id=?',Date.now(),player.id)]);return json({ok:true,revision:room.revision+1});}
if(action==='input'&&request.method==='POST'){await findRoom(env,id);const {player}=await member(request,env,id),b=await body(request,16000),input=validateInput(b);await query(env,'UPDATE players SET input=?,seq=?,seen_at=? WHERE id=? AND seq<?',JSON.stringify(input),b.seq,Date.now(),player.id,b.seq).run();return json({ok:true});}
if(action==='leave'&&request.method==='POST'){const {player,hashed}=await member(request,env,id),room=await findRoom(env,id);if(hashed===room.host_token)await query(env,"UPDATE rooms SET status='closed',updated_at=? WHERE id=?",Date.now(),id).run();await query(env,'DELETE FROM players WHERE id=?',player.id).run();return json({ok:true});}
fail('ไม่รองรับคำสั่งนี้',405);
}catch(error){if(String(error.message).includes('UNIQUE constraint'))return json({error:'ตำแหน่งนี้มีผู้เล่นแล้ว เลือกตำแหน่งหรือทีมอื่น'},409);if(error.status)return json({error:error.message},error.status);console.error('Room service failure',error.message);return json({error:'เชื่อมต่อห้องไม่สำเร็จ ลองใหม่อีกครั้ง'},503);}}
export default {async fetch(request,env,ctx){const url=new URL(request.url);if(/^\/api\/(teachers|lesson-banks|classes)(\/|$)/.test(url.pathname))return classroomApi(request,env,{heroIds:HERO_IDS,validateInput,validateState});if(url.pathname.startsWith('/api/'))return api(request,env);if(typeof SITE_ASSETS!=='undefined'){const asset=SITE_ASSETS[url.pathname==='/'?'/index.html':url.pathname];if(asset){const content=asset.binary?Uint8Array.from(atob(asset.body),c=>c.charCodeAt(0)):asset.body;return new Response(content,{headers:{'content-type':asset.type,'cache-control':url.pathname.startsWith('/assets/')?'public, max-age=86400':'no-cache','x-content-type-options':'nosniff'}});}}return new Response('Not found',{status:404});}};
